include /build/source/fbpanel/fbpanel-6.1/config.mk

SRCS = main.c fixedtip.c eggtraymanager.c egg-marshal.c 
LIBTARGET = tray.so
install:
	$(install) 755 $(LIBDIR)/fbpanel 755 $(LIBTARGET)

include /build/source/fbpanel/fbpanel-6.1/rules.mk
