#! /bin/sh
# $Aumix: aumix/src/mute,v 1.2 2010/04/28 23:30:37 trevor Exp $
# Copyright (c) 2001, Ben Ford and Trevor Johnson
#
# Run this script to mute, then again to un-mute.
# Note:  it will clobber your saved settings.
#
volumes=$(aumix -vq |tr -d ,)
if [ $(echo $volumes | awk '{print $2}') -ne 0 -o \
	$(echo $volumes | awk '{print $3}') -ne 0 ]; then
	aumix -S
	aumix -v 0
else
	aumix -L > /dev/null
fi
