.\" man page originally for the Debian/GNU Linux system
.TH FBPANEL "1" "February 2004" "fbpanel 2.2" "User Commands"
.SH NAME
fbpanel \- a lightweight GTK2-based panel for UNIX desktop.
.SH SYNOPSIS
.B fbpanel
[\fIOPTION\fR]
.br
.SH DESCRIPTION
.PP
fbpanel is desktop panel which provides graphical information and feedback about 
desktop activity and allows interaction with the window manager. 
It features:
.HP
\(bu taskbar \- shows a list of the managed windows (tasks)
.HP
\(bu pager \- thumbnailed view of the desktop.
.HP
\(bu launchbar \- buttons to quickly launch applications
.HP
\(bu show desktop \- button to iconify or shade all windows 
.HP
\(bu image \- display an image
.HP
\(bu clock \- show the current time and/or date
.HP
\(bu system tray \- tray for XEMBED icons (aka docklets)
.PP
fbpanel requires NETWM (www.freedesktop.org) compliant window manager. 
You can run many instances of fbpanel each with its own configuration
(see \fBOPTIONS\fR below).

Most updated info about fbpanel can be found on its home page:
http://fbpanel.sf.net/

.SH OPTIONS
.TP
\fB\-h\fR
\- print help message and exit.
.TP
\fB\-v\fR
\- print version and exit.
.TP
\fB\-p <name>\fR 
\- use the profile <name>. The profile is loaded from the file ~/.fbpanel/<name>.
If that fails, fbpanel will load PREFIX/share/fbpanel/<name>. No \fB\-p\fR option is equivalent
to \fB\-p default\fR 
.SH CUSTOMIZATION
To change default settings, copy profile file to your home directory
.br
      mkdir -p ~/.fbpanel
      cp PREFIX/share/fbpanel/default ~/.fbpanel
.br
and edit it. Default profile file contains comments and explanation inside,
so it should be easy. For full list of options please visit fbpanel's home page.

.SH FILES
.TP
PREFIX/share/fbpanel
Directory with system-wide resources and default settings
.TP
~/.fbpanel/
Directory with the user's private profiles
.TP
~/.fbpanel/default
The user's default profile.
.SH AUTHOR
fbpanel was written by Anatoly Asviyan <aanatoly@users.sf.net>.
This manual page was originally written for the
Debian GNU/Linux system by Shyamal Prasad <shyamal@member.fsf.org>.
