.TH xcb_copy_area 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_copy_area \- copy areas
.SH SYNOPSIS
.hy 0
.B #include <xcb/xproto.h>
.SS Request function
.HP
xcb_void_cookie_t \fBxcb_copy_area\fP(xcb_connection_t\ *\fIconn\fP, xcb_drawable_t\ \fIsrc_drawable\fP, xcb_drawable_t\ \fIdst_drawable\fP, xcb_gcontext_t\ \fIgc\fP, int16_t\ \fIsrc_x\fP, int16_t\ \fIsrc_y\fP, int16_t\ \fIdst_x\fP, int16_t\ \fIdst_y\fP, uint16_t\ \fIwidth\fP, uint16_t\ \fIheight\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIsrc_drawable\fP 1i
The source drawable (Window or Pixmap).
.IP \fIdst_drawable\fP 1i
The destination drawable (Window or Pixmap).
.IP \fIgc\fP 1i
The graphics context to use.
.IP \fIsrc_x\fP 1i
The source X coordinate.
.IP \fIsrc_y\fP 1i
The source Y coordinate.
.IP \fIdst_x\fP 1i
The destination X coordinate.
.IP \fIdst_y\fP 1i
The destination Y coordinate.
.IP \fIwidth\fP 1i
The width of the area to copy (in pixels).
.IP \fIheight\fP 1i
The height of the area to copy (in pixels).
.SH DESCRIPTION
Copies the specified rectangle from \fIsrc_drawable\fP to \fIdst_drawable\fP.
.SH RETURN VALUE
Returns an \fIxcb_void_cookie_t\fP. Errors (if any) have to be handled in the event loop.

If you want to handle errors directly with \fIxcb_request_check\fP instead, use \fIxcb_copy_area_checked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
.IP \fIxcb_drawable_error_t\fP 1i
The specified \fIdrawable\fP (Window or Pixmap) does not exist.
.IP \fIxcb_g_context_error_t\fP 1i
The specified graphics context does not exist.
.IP \fIxcb_match_error_t\fP 1i
\fIsrc_drawable\fP has a different root or depth than \fIdst_drawable\fP.
.SH SEE ALSO
.BR xcb-requests (3)
.SH AUTHOR
Generated from xproto.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
