.TH xcb_dri2_swap_buffers 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_dri2_swap_buffers \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/dri2.h>
.SS Request function
.HP
xcb_dri2_swap_buffers_cookie_t \fBxcb_dri2_swap_buffers\fP(xcb_connection_t\ *\fIconn\fP, xcb_drawable_t\ \fIdrawable\fP, uint32_t\ \fItarget_msc_hi\fP, uint32_t\ \fItarget_msc_lo\fP, uint32_t\ \fIdivisor_hi\fP, uint32_t\ \fIdivisor_lo\fP, uint32_t\ \fIremainder_hi\fP, uint32_t\ \fIremainder_lo\fP);
.PP
.SS Reply datastructure
.nf
.sp
typedef struct xcb_dri2_swap_buffers_reply_t {
    uint8_t  \fIresponse_type\fP;
    uint8_t  \fIpad0\fP;
    uint16_t \fIsequence\fP;
    uint32_t \fIlength\fP;
    uint32_t \fIswap_hi\fP;
    uint32_t \fIswap_lo\fP;
} \fBxcb_dri2_swap_buffers_reply_t\fP;
.fi
.SS Reply function
.HP
xcb_dri2_swap_buffers_reply_t *\fBxcb_dri2_swap_buffers_reply\fP(xcb_connection_t\ *\fIconn\fP, xcb_dri2_swap_buffers_cookie_t\ \fIcookie\fP, xcb_generic_error_t\ **\fIe\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIdrawable\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fItarget_msc_hi\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fItarget_msc_lo\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdivisor_hi\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdivisor_lo\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIremainder_hi\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIremainder_lo\fP 1i
TODO: NOT YET DOCUMENTED.
.SH REPLY FIELDS
.IP \fIresponse_type\fP 1i
The type of this reply, in this case \fIXCB_DRI2_SWAP_BUFFERS\fP. This field is also present in the \fIxcb_generic_reply_t\fP and can be used to tell replies apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIlength\fP 1i
The length of the reply, in words (a word is 4 bytes).
.IP \fIswap_hi\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIswap_lo\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_dri2_swap_buffers_cookie_t\fP. Errors have to be handled when calling the reply function \fIxcb_dri2_swap_buffers_reply\fP.

If you want to handle errors in the event loop instead, use \fIxcb_dri2_swap_buffers_unchecked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from dri2.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
