.TH xcb_input_set_device_modifier_mapping 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_input_set_device_modifier_mapping \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xinput.h>
.SS Request function
.HP
xcb_input_set_device_modifier_mapping_cookie_t \fBxcb_input_set_device_modifier_mapping\fP(xcb_connection_t\ *\fIconn\fP, uint8_t\ \fIdevice_id\fP, uint8_t\ \fIkeycodes_per_modifier\fP, const uint8_t\ *\fIkeymaps\fP);
.PP
.SS Reply datastructure
.nf
.sp
typedef struct xcb_input_set_device_modifier_mapping_reply_t {
    uint8_t  \fIresponse_type\fP;
    uint8_t  \fIpad0\fP;
    uint16_t \fIsequence\fP;
    uint32_t \fIlength\fP;
    uint8_t  \fIstatus\fP;
    uint8_t  \fIpad1\fP[23];
} \fBxcb_input_set_device_modifier_mapping_reply_t\fP;
.fi
.SS Reply function
.HP
xcb_input_set_device_modifier_mapping_reply_t *\fBxcb_input_set_device_modifier_mapping_reply\fP(xcb_connection_t\ *\fIconn\fP, xcb_input_set_device_modifier_mapping_cookie_t\ \fIcookie\fP, xcb_generic_error_t\ **\fIe\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIdevice_id\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIkeycodes_per_modifier\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIkeymaps\fP 1i
TODO: NOT YET DOCUMENTED.
.SH REPLY FIELDS
.IP \fIresponse_type\fP 1i
The type of this reply, in this case \fIXCB_INPUT_SET_DEVICE_MODIFIER_MAPPING\fP. This field is also present in the \fIxcb_generic_reply_t\fP and can be used to tell replies apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIlength\fP 1i
The length of the reply, in words (a word is 4 bytes).
.IP \fIstatus\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_input_set_device_modifier_mapping_cookie_t\fP. Errors have to be handled when calling the reply function \fIxcb_input_set_device_modifier_mapping_reply\fP.

If you want to handle errors in the event loop instead, use \fIxcb_input_set_device_modifier_mapping_unchecked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from xinput.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
