.TH xcb_randr_screen_change_notify_event_t 3  "libxcb 1.11" "X Version 11" "XCB Events"
.ad l
.SH NAME
xcb_randr_screen_change_notify_event_t \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/randr.h>
.PP
.SS Event datastructure
.nf
.sp
typedef struct xcb_randr_screen_change_notify_event_t {
    uint8_t         \fIresponse_type\fP;
    uint8_t         \fIrotation\fP;
    uint16_t        \fIsequence\fP;
    xcb_timestamp_t \fItimestamp\fP;
    xcb_timestamp_t \fIconfig_timestamp\fP;
    xcb_window_t    \fIroot\fP;
    xcb_window_t    \fIrequest_window\fP;
    uint16_t        \fIsizeID\fP;
    uint16_t        \fIsubpixel_order\fP;
    uint16_t        \fIwidth\fP;
    uint16_t        \fIheight\fP;
    uint16_t        \fImwidth\fP;
    uint16_t        \fImheight\fP;
} \fBxcb_randr_screen_change_notify_event_t\fP;
.fi
.br
.hy 1
.SH EVENT FIELDS
.IP \fIresponse_type\fP 1i
The type of this event, in this case \fIXCB_RANDR_SCREEN_CHANGE_NOTIFY\fP. This field is also present in the \fIxcb_generic_event_t\fP and can be used to tell events apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIrotation\fP 1i
NOT YET DOCUMENTED.
.IP \fItimestamp\fP 1i
NOT YET DOCUMENTED.
.IP \fIconfig_timestamp\fP 1i
NOT YET DOCUMENTED.
.IP \fIroot\fP 1i
NOT YET DOCUMENTED.
.IP \fIrequest_window\fP 1i
NOT YET DOCUMENTED.
.IP \fIsizeID\fP 1i
NOT YET DOCUMENTED.
.IP \fIsubpixel_order\fP 1i
NOT YET DOCUMENTED.
.IP \fIwidth\fP 1i
NOT YET DOCUMENTED.
.IP \fIheight\fP 1i
NOT YET DOCUMENTED.
.IP \fImwidth\fP 1i
NOT YET DOCUMENTED.
.IP \fImheight\fP 1i
NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH SEE ALSO
.SH AUTHOR
Generated from randr.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
