.TH xcb_present_redirect_notify_event_t 3  "libxcb 1.11" "X Version 11" "XCB Events"
.ad l
.SH NAME
xcb_present_redirect_notify_event_t \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/present.h>
.PP
.SS Event datastructure
.nf
.sp
typedef struct xcb_present_redirect_notify_event_t {
    uint8_t             \fIresponse_type\fP;
    uint8_t             \fIextension\fP;
    uint16_t            \fIsequence\fP;
    uint32_t            \fIlength\fP;
    uint16_t            \fIevent_type\fP;
    uint8_t             \fIupdate_window\fP;
    uint8_t             \fIpad0\fP;
    xcb_present_event_t \fIevent\fP;
    xcb_window_t        \fIevent_window\fP;
    xcb_window_t        \fIwindow\fP;
    xcb_pixmap_t        \fIpixmap\fP;
    uint32_t            \fIserial\fP;
    uint32_t            \fIfull_sequence\fP;
    xcb_xfixes_region_t \fIvalid_region\fP;
    xcb_xfixes_region_t \fIupdate_region\fP;
    xcb_rectangle_t     \fIvalid_rect\fP;
    xcb_rectangle_t     \fIupdate_rect\fP;
    int16_t             \fIx_off\fP;
    int16_t             \fIy_off\fP;
    xcb_randr_crtc_t    \fItarget_crtc\fP;
    xcb_sync_fence_t    \fIwait_fence\fP;
    xcb_sync_fence_t    \fIidle_fence\fP;
    uint32_t            \fIoptions\fP;
    uint8_t             \fIpad1\fP[4];
    uint64_t            \fItarget_msc\fP;
    uint64_t            \fIdivisor\fP;
    uint64_t            \fIremainder\fP;
} \fBxcb_present_redirect_notify_event_t\fP;
.fi
.br
.hy 1
.SH EVENT FIELDS
.IP \fIresponse_type\fP 1i
The type of this event, in this case \fIXCB_PRESENT_REDIRECT_NOTIFY\fP. This field is also present in the \fIxcb_generic_event_t\fP and can be used to tell events apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIextension\fP 1i
NOT YET DOCUMENTED.
.IP \fIlength\fP 1i
NOT YET DOCUMENTED.
.IP \fIevent_type\fP 1i
NOT YET DOCUMENTED.
.IP \fIupdate_window\fP 1i
NOT YET DOCUMENTED.
.IP \fIevent\fP 1i
NOT YET DOCUMENTED.
.IP \fIevent_window\fP 1i
NOT YET DOCUMENTED.
.IP \fIwindow\fP 1i
NOT YET DOCUMENTED.
.IP \fIpixmap\fP 1i
NOT YET DOCUMENTED.
.IP \fIserial\fP 1i
NOT YET DOCUMENTED.
.IP \fIfull_sequence\fP 1i
NOT YET DOCUMENTED.
.IP \fIvalid_region\fP 1i
NOT YET DOCUMENTED.
.IP \fIupdate_region\fP 1i
NOT YET DOCUMENTED.
.IP \fIvalid_rect\fP 1i
NOT YET DOCUMENTED.
.IP \fIupdate_rect\fP 1i
NOT YET DOCUMENTED.
.IP \fIx_off\fP 1i
NOT YET DOCUMENTED.
.IP \fIy_off\fP 1i
NOT YET DOCUMENTED.
.IP \fItarget_crtc\fP 1i
NOT YET DOCUMENTED.
.IP \fIwait_fence\fP 1i
NOT YET DOCUMENTED.
.IP \fIidle_fence\fP 1i
NOT YET DOCUMENTED.
.IP \fIoptions\fP 1i
NOT YET DOCUMENTED.
.IP \fItarget_msc\fP 1i
NOT YET DOCUMENTED.
.IP \fIdivisor\fP 1i
NOT YET DOCUMENTED.
.IP \fIremainder\fP 1i
NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH SEE ALSO
.SH AUTHOR
Generated from present.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
