.TH xcb_set_clip_rectangles 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_set_clip_rectangles \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xproto.h>
.SS Request function
.HP
xcb_void_cookie_t \fBxcb_set_clip_rectangles\fP(xcb_connection_t\ *\fIconn\fP, uint8_t\ \fIordering\fP, xcb_gcontext_t\ \fIgc\fP, int16_t\ \fIclip_x_origin\fP, int16_t\ \fIclip_y_origin\fP, uint32_t\ \fIrectangles_len\fP, const xcb_rectangle_t\ *\fIrectangles\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIordering\fP 1i
One of the following values:
.RS 1i
.IP \fIXCB_CLIP_ORDERING_UNSORTED\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_CLIP_ORDERING_Y_SORTED\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_CLIP_ORDERING_YX_SORTED\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_CLIP_ORDERING_YX_BANDED\fP 1i
TODO: NOT YET DOCUMENTED.
.RE
.RS 1i
TODO: NOT YET DOCUMENTED.
.RE
.IP \fIgc\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIclip_x_origin\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIclip_y_origin\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIrectangles_len\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIrectangles\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_void_cookie_t\fP. Errors (if any) have to be handled in the event loop.

If you want to handle errors directly with \fIxcb_request_check\fP instead, use \fIxcb_set_clip_rectangles_checked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from xproto.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
