.TH xcb_query_best_size 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_query_best_size \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xproto.h>
.SS Request function
.HP
xcb_query_best_size_cookie_t \fBxcb_query_best_size\fP(xcb_connection_t\ *\fIconn\fP, uint8_t\ \fI_class\fP, xcb_drawable_t\ \fIdrawable\fP, uint16_t\ \fIwidth\fP, uint16_t\ \fIheight\fP);
.PP
.SS Reply datastructure
.nf
.sp
typedef struct xcb_query_best_size_reply_t {
    uint8_t  \fIresponse_type\fP;
    uint8_t  \fIpad0\fP;
    uint16_t \fIsequence\fP;
    uint32_t \fIlength\fP;
    uint16_t \fIwidth\fP;
    uint16_t \fIheight\fP;
} \fBxcb_query_best_size_reply_t\fP;
.fi
.SS Reply function
.HP
xcb_query_best_size_reply_t *\fBxcb_query_best_size_reply\fP(xcb_connection_t\ *\fIconn\fP, xcb_query_best_size_cookie_t\ \fIcookie\fP, xcb_generic_error_t\ **\fIe\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fI_class\fP 1i
One of the following values:
.RS 1i
.IP \fIXCB_QUERY_SHAPE_OF_LARGEST_CURSOR\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_QUERY_SHAPE_OF_FASTEST_TILE\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_QUERY_SHAPE_OF_FASTEST_STIPPLE\fP 1i
TODO: NOT YET DOCUMENTED.
.RE
.RS 1i
TODO: NOT YET DOCUMENTED.
.RE
.IP \fIdrawable\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIwidth\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIheight\fP 1i
TODO: NOT YET DOCUMENTED.
.SH REPLY FIELDS
.IP \fIresponse_type\fP 1i
The type of this reply, in this case \fIXCB_QUERY_BEST_SIZE\fP. This field is also present in the \fIxcb_generic_reply_t\fP and can be used to tell replies apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIlength\fP 1i
The length of the reply, in words (a word is 4 bytes).
.IP \fIwidth\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIheight\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_query_best_size_cookie_t\fP. Errors have to be handled when calling the reply function \fIxcb_query_best_size_reply\fP.

If you want to handle errors in the event loop instead, use \fIxcb_query_best_size_unchecked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from xproto.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
