.TH xcb_xf86dri_get_client_driver_name 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_xf86dri_get_client_driver_name \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xf86dri.h>
.SS Request function
.HP
xcb_xf86dri_get_client_driver_name_cookie_t \fBxcb_xf86dri_get_client_driver_name\fP(xcb_connection_t\ *\fIconn\fP, uint32_t\ \fIscreen\fP);
.PP
.SS Reply datastructure
.nf
.sp
typedef struct xcb_xf86dri_get_client_driver_name_reply_t {
    uint8_t  \fIresponse_type\fP;
    uint8_t  \fIpad0\fP;
    uint16_t \fIsequence\fP;
    uint32_t \fIlength\fP;
    uint32_t \fIclient_driver_major_version\fP;
    uint32_t \fIclient_driver_minor_version\fP;
    uint32_t \fIclient_driver_patch_version\fP;
    uint32_t \fIclient_driver_name_len\fP;
    uint8_t  \fIpad1\fP[8];
} \fBxcb_xf86dri_get_client_driver_name_reply_t\fP;
.fi
.SS Reply function
.HP
xcb_xf86dri_get_client_driver_name_reply_t *\fBxcb_xf86dri_get_client_driver_name_reply\fP(xcb_connection_t\ *\fIconn\fP, xcb_xf86dri_get_client_driver_name_cookie_t\ \fIcookie\fP, xcb_generic_error_t\ **\fIe\fP);
.SS Reply accessors
.HP
char *\fBxcb_xf86dri_get_client_driver_name_client_driver_name\fP(const xcb_xf86dri_get_client_driver_name_request_t *\fIreply\fP);
.HP
int \fBxcb_xf86dri_get_client_driver_name_client_driver_name_length\fP(const xcb_xf86dri_get_client_driver_name_reply_t *\fIreply\fP);
.HP
xcb_generic_iterator_t \fBxcb_xf86dri_get_client_driver_name_client_driver_name_end\fP(const xcb_xf86dri_get_client_driver_name_reply_t *\fIreply\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIscreen\fP 1i
TODO: NOT YET DOCUMENTED.
.SH REPLY FIELDS
.IP \fIresponse_type\fP 1i
The type of this reply, in this case \fIXCB_XF86DRI_GET_CLIENT_DRIVER_NAME\fP. This field is also present in the \fIxcb_generic_reply_t\fP and can be used to tell replies apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIlength\fP 1i
The length of the reply, in words (a word is 4 bytes).
.IP \fIclient_driver_major_version\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIclient_driver_minor_version\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIclient_driver_patch_version\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIclient_driver_name_len\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_xf86dri_get_client_driver_name_cookie_t\fP. Errors have to be handled when calling the reply function \fIxcb_xf86dri_get_client_driver_name_reply\fP.

If you want to handle errors in the event loop instead, use \fIxcb_xf86dri_get_client_driver_name_unchecked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from xf86dri.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
