.TH xcb_x_print_print_get_page_dimensions 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_x_print_print_get_page_dimensions \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xprint.h>
.SS Request function
.HP
xcb_x_print_print_get_page_dimensions_cookie_t \fBxcb_x_print_print_get_page_dimensions\fP(xcb_connection_t\ *\fIconn\fP, xcb_x_print_pcontext_t\ \fIcontext\fP);
.PP
.SS Reply datastructure
.nf
.sp
typedef struct xcb_x_print_print_get_page_dimensions_reply_t {
    uint8_t  \fIresponse_type\fP;
    uint8_t  \fIpad0\fP;
    uint16_t \fIsequence\fP;
    uint32_t \fIlength\fP;
    uint16_t \fIwidth\fP;
    uint16_t \fIheight\fP;
    uint16_t \fIoffset_x\fP;
    uint16_t \fIoffset_y\fP;
    uint16_t \fIreproducible_width\fP;
    uint16_t \fIreproducible_height\fP;
} \fBxcb_x_print_print_get_page_dimensions_reply_t\fP;
.fi
.SS Reply function
.HP
xcb_x_print_print_get_page_dimensions_reply_t *\fBxcb_x_print_print_get_page_dimensions_reply\fP(xcb_connection_t\ *\fIconn\fP, xcb_x_print_print_get_page_dimensions_cookie_t\ \fIcookie\fP, xcb_generic_error_t\ **\fIe\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIcontext\fP 1i
TODO: NOT YET DOCUMENTED.
.SH REPLY FIELDS
.IP \fIresponse_type\fP 1i
The type of this reply, in this case \fIXCB_X_PRINT_PRINT_GET_PAGE_DIMENSIONS\fP. This field is also present in the \fIxcb_generic_reply_t\fP and can be used to tell replies apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIlength\fP 1i
The length of the reply, in words (a word is 4 bytes).
.IP \fIwidth\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIheight\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIoffset_x\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIoffset_y\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIreproducible_width\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIreproducible_height\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_x_print_print_get_page_dimensions_cookie_t\fP. Errors have to be handled when calling the reply function \fIxcb_x_print_print_get_page_dimensions_reply\fP.

If you want to handle errors in the event loop instead, use \fIxcb_x_print_print_get_page_dimensions_unchecked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from xprint.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
