.TH xcb_get_window_attributes 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_get_window_attributes \- Gets window attributes
.SH SYNOPSIS
.hy 0
.B #include <xcb/xproto.h>
.SS Request function
.HP
xcb_get_window_attributes_cookie_t \fBxcb_get_window_attributes\fP(xcb_connection_t\ *\fIconn\fP, xcb_window_t\ \fIwindow\fP);
.PP
.SS Reply datastructure
.nf
.sp
typedef struct xcb_get_window_attributes_reply_t {
    uint8_t        \fIresponse_type\fP;
    uint8_t        \fIbacking_store\fP;
    uint16_t       \fIsequence\fP;
    uint32_t       \fIlength\fP;
    xcb_visualid_t \fIvisual\fP;
    uint16_t       \fI_class\fP;
    uint8_t        \fIbit_gravity\fP;
    uint8_t        \fIwin_gravity\fP;
    uint32_t       \fIbacking_planes\fP;
    uint32_t       \fIbacking_pixel\fP;
    uint8_t        \fIsave_under\fP;
    uint8_t        \fImap_is_installed\fP;
    uint8_t        \fImap_state\fP;
    uint8_t        \fIoverride_redirect\fP;
    xcb_colormap_t \fIcolormap\fP;
    uint32_t       \fIall_event_masks\fP;
    uint32_t       \fIyour_event_mask\fP;
    uint16_t       \fIdo_not_propagate_mask\fP;
    uint8_t        \fIpad0\fP[2];
} \fBxcb_get_window_attributes_reply_t\fP;
.fi
.SS Reply function
.HP
xcb_get_window_attributes_reply_t *\fBxcb_get_window_attributes_reply\fP(xcb_connection_t\ *\fIconn\fP, xcb_get_window_attributes_cookie_t\ \fIcookie\fP, xcb_generic_error_t\ **\fIe\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIwindow\fP 1i
The window to get the attributes from.
.SH REPLY FIELDS
.IP \fIresponse_type\fP 1i
The type of this reply, in this case \fIXCB_GET_WINDOW_ATTRIBUTES\fP. This field is also present in the \fIxcb_generic_reply_t\fP and can be used to tell replies apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIlength\fP 1i
The length of the reply, in words (a word is 4 bytes).
.IP \fIbacking_store\fP 1i
One of the following values:
.RS 1i
.IP \fIXCB_BACKING_STORE_NOT_USEFUL\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_BACKING_STORE_WHEN_MAPPED\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_BACKING_STORE_ALWAYS\fP 1i
TODO: NOT YET DOCUMENTED.
.RE
.RS 1i


.RE
.IP \fIvisual\fP 1i
The associated visual structure of \fIwindow\fP.
.IP \fI_class\fP 1i
One of the following values:
.RS 1i
.IP \fIXCB_WINDOW_CLASS_COPY_FROM_PARENT\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_WINDOW_CLASS_INPUT_OUTPUT\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_WINDOW_CLASS_INPUT_ONLY\fP 1i
TODO: NOT YET DOCUMENTED.
.RE
.RS 1i


.RE
.IP \fIbit_gravity\fP 1i
One of the following values:
.RS 1i
.IP \fIXCB_GRAVITY_BIT_FORGET\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_WIN_UNMAP\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_NORTH_WEST\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_NORTH\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_NORTH_EAST\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_WEST\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_CENTER\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_EAST\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_SOUTH_WEST\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_SOUTH\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_SOUTH_EAST\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_STATIC\fP 1i
TODO: NOT YET DOCUMENTED.
.RE
.RS 1i


.RE
.IP \fIwin_gravity\fP 1i
One of the following values:
.RS 1i
.IP \fIXCB_GRAVITY_BIT_FORGET\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_WIN_UNMAP\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_NORTH_WEST\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_NORTH\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_NORTH_EAST\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_WEST\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_CENTER\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_EAST\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_SOUTH_WEST\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_SOUTH\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_SOUTH_EAST\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_GRAVITY_STATIC\fP 1i
TODO: NOT YET DOCUMENTED.
.RE
.RS 1i


.RE
.IP \fIbacking_planes\fP 1i
Planes to be preserved if possible.
.IP \fIbacking_pixel\fP 1i
Value to be used when restoring planes.
.IP \fIsave_under\fP 1i
Boolean, should bits under be saved?
.IP \fImap_is_installed\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fImap_state\fP 1i
One of the following values:
.RS 1i
.IP \fIXCB_MAP_STATE_UNMAPPED\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_MAP_STATE_UNVIEWABLE\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_MAP_STATE_VIEWABLE\fP 1i
TODO: NOT YET DOCUMENTED.
.RE
.RS 1i


.RE
.IP \fIoverride_redirect\fP 1i
Window managers should ignore this window if \fIoverride_redirect\fP is 1.
.IP \fIcolormap\fP 1i
Color map to be associated with window.
.IP \fIall_event_masks\fP 1i
Set of events all people have interest in.
.IP \fIyour_event_mask\fP 1i
My event mask.
.IP \fIdo_not_propagate_mask\fP 1i
Set of events that should not propagate.
.SH DESCRIPTION
Gets the current attributes for the specified \fIwindow\fP.
.SH RETURN VALUE
Returns an \fIxcb_get_window_attributes_cookie_t\fP. Errors have to be handled when calling the reply function \fIxcb_get_window_attributes_reply\fP.

If you want to handle errors in the event loop instead, use \fIxcb_get_window_attributes_unchecked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
.IP \fIxcb_drawable_error_t\fP 1i
TODO: reasons?
.IP \fIxcb_window_error_t\fP 1i
The specified \fIwindow\fP does not exist.
.SH SEE ALSO
.BR xcb-requests (3)
.SH AUTHOR
Generated from xproto.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
