.TH xcb_input_touch_begin_event_t 3  "libxcb 1.11" "X Version 11" "XCB Events"
.ad l
.SH NAME
xcb_input_touch_begin_event_t \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xinput.h>
.PP
.SS Event datastructure
.nf
.sp
typedef struct xcb_input_touch_begin_event_t {
    uint8_t                   \fIresponse_type\fP;
    uint8_t                   \fIextension\fP;
    uint16_t                  \fIsequence\fP;
    uint32_t                  \fIlength\fP;
    uint16_t                  \fIevent_type\fP;
    xcb_input_device_id_t     \fIdeviceid\fP;
    xcb_timestamp_t           \fItime\fP;
    uint32_t                  \fIdetail\fP;
    xcb_window_t              \fIroot\fP;
    xcb_window_t              \fIevent\fP;
    xcb_window_t              \fIchild\fP;
    uint32_t                  \fIfull_sequence\fP;
    xcb_input_fp1616_t        \fIroot_x\fP;
    xcb_input_fp1616_t        \fIroot_y\fP;
    xcb_input_fp1616_t        \fIevent_x\fP;
    xcb_input_fp1616_t        \fIevent_y\fP;
    uint16_t                  \fIbuttons_len\fP;
    uint16_t                  \fIvaluators_len\fP;
    xcb_input_device_id_t     \fIsourceid\fP;
    uint8_t                   \fIpad0\fP[2];
    uint32_t                  \fIflags\fP;
    xcb_input_modifier_info_t \fImods\fP;
    xcb_input_group_info_t    \fIgroup\fP;
} \fBxcb_input_touch_begin_event_t\fP;
.fi
.br
.hy 1
.SH EVENT FIELDS
.IP \fIresponse_type\fP 1i
The type of this event, in this case \fIXCB_INPUT_TOUCH_BEGIN\fP. This field is also present in the \fIxcb_generic_event_t\fP and can be used to tell events apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIextension\fP 1i
NOT YET DOCUMENTED.
.IP \fIlength\fP 1i
NOT YET DOCUMENTED.
.IP \fIevent_type\fP 1i
NOT YET DOCUMENTED.
.IP \fIdeviceid\fP 1i
NOT YET DOCUMENTED.
.IP \fItime\fP 1i
NOT YET DOCUMENTED.
.IP \fIdetail\fP 1i
NOT YET DOCUMENTED.
.IP \fIroot\fP 1i
NOT YET DOCUMENTED.
.IP \fIevent\fP 1i
NOT YET DOCUMENTED.
.IP \fIchild\fP 1i
NOT YET DOCUMENTED.
.IP \fIfull_sequence\fP 1i
NOT YET DOCUMENTED.
.IP \fIroot_x\fP 1i
NOT YET DOCUMENTED.
.IP \fIroot_y\fP 1i
NOT YET DOCUMENTED.
.IP \fIevent_x\fP 1i
NOT YET DOCUMENTED.
.IP \fIevent_y\fP 1i
NOT YET DOCUMENTED.
.IP \fIbuttons_len\fP 1i
NOT YET DOCUMENTED.
.IP \fIvaluators_len\fP 1i
NOT YET DOCUMENTED.
.IP \fIsourceid\fP 1i
NOT YET DOCUMENTED.
.IP \fIflags\fP 1i
NOT YET DOCUMENTED.
.IP \fImods\fP 1i
NOT YET DOCUMENTED.
.IP \fIgroup\fP 1i
NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH SEE ALSO
.SH AUTHOR
Generated from xinput.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
