.TH xcb_change_hosts 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_change_hosts \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xproto.h>
.SS Request function
.HP
xcb_void_cookie_t \fBxcb_change_hosts\fP(xcb_connection_t\ *\fIconn\fP, uint8_t\ \fImode\fP, uint8_t\ \fIfamily\fP, uint16_t\ \fIaddress_len\fP, const uint8_t\ *\fIaddress\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fImode\fP 1i
One of the following values:
.RS 1i
.IP \fIXCB_HOST_MODE_INSERT\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_HOST_MODE_DELETE\fP 1i
TODO: NOT YET DOCUMENTED.
.RE
.RS 1i
TODO: NOT YET DOCUMENTED.
.RE
.IP \fIfamily\fP 1i
One of the following values:
.RS 1i
.IP \fIXCB_FAMILY_INTERNET\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_FAMILY_DECNET\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_FAMILY_CHAOS\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_FAMILY_SERVER_INTERPRETED\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_FAMILY_INTERNET_6\fP 1i
TODO: NOT YET DOCUMENTED.
.RE
.RS 1i
TODO: NOT YET DOCUMENTED.
.RE
.IP \fIaddress_len\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIaddress\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_void_cookie_t\fP. Errors (if any) have to be handled in the event loop.

If you want to handle errors directly with \fIxcb_request_check\fP instead, use \fIxcb_change_hosts_checked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from xproto.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
