.TH xcb_xkb_set_named_indicator 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_xkb_set_named_indicator \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xkb.h>
.SS Request function
.HP
xcb_void_cookie_t \fBxcb_xkb_set_named_indicator\fP(xcb_connection_t\ *\fIconn\fP, xcb_xkb_device_spec_t\ \fIdeviceSpec\fP, xcb_xkb_led_class_spec_t\ \fIledClass\fP, xcb_xkb_id_spec_t\ \fIledID\fP, xcb_atom_t\ \fIindicator\fP, uint8_t\ \fIsetState\fP, uint8_t\ \fIon\fP, uint8_t\ \fIsetMap\fP, uint8_t\ \fIcreateMap\fP, uint8_t\ \fImap_flags\fP, uint8_t\ \fImap_whichGroups\fP, uint8_t\ \fImap_groups\fP, uint8_t\ \fImap_whichMods\fP, uint8_t\ \fImap_realMods\fP, uint16_t\ \fImap_vmods\fP, uint32_t\ \fImap_ctrls\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIdeviceSpec\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIledClass\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIledID\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIindicator\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIsetState\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIon\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIsetMap\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIcreateMap\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fImap_flags\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fImap_whichGroups\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fImap_groups\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fImap_whichMods\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fImap_realMods\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fImap_vmods\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fImap_ctrls\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_void_cookie_t\fP. Errors (if any) have to be handled in the event loop.

If you want to handle errors directly with \fIxcb_request_check\fP instead, use \fIxcb_xkb_set_named_indicator_checked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from xkb.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
