.TH xcb_record_enable_context 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_record_enable_context \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/record.h>
.SS Request function
.HP
xcb_record_enable_context_cookie_t \fBxcb_record_enable_context\fP(xcb_connection_t\ *\fIconn\fP, xcb_record_context_t\ \fIcontext\fP);
.PP
.SS Reply datastructure
.nf
.sp
typedef struct xcb_record_enable_context_reply_t {
    uint8_t                     \fIresponse_type\fP;
    uint8_t                     \fIcategory\fP;
    uint16_t                    \fIsequence\fP;
    uint32_t                    \fIlength\fP;
    xcb_record_element_header_t \fIelement_header\fP;
    uint8_t                     \fIclient_swapped\fP;
    uint8_t                     \fIpad0\fP[2];
    uint32_t                    \fIxid_base\fP;
    uint32_t                    \fIserver_time\fP;
    uint32_t                    \fIrec_sequence_num\fP;
    uint8_t                     \fIpad1\fP[8];
} \fBxcb_record_enable_context_reply_t\fP;
.fi
.SS Reply function
.HP
xcb_record_enable_context_reply_t *\fBxcb_record_enable_context_reply\fP(xcb_connection_t\ *\fIconn\fP, xcb_record_enable_context_cookie_t\ \fIcookie\fP, xcb_generic_error_t\ **\fIe\fP);
.SS Reply accessors
.HP
uint8_t *\fBxcb_record_enable_context_data\fP(const xcb_record_enable_context_request_t *\fIreply\fP);
.HP
int \fBxcb_record_enable_context_data_length\fP(const xcb_record_enable_context_reply_t *\fIreply\fP);
.HP
xcb_generic_iterator_t \fBxcb_record_enable_context_data_end\fP(const xcb_record_enable_context_reply_t *\fIreply\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIcontext\fP 1i
TODO: NOT YET DOCUMENTED.
.SH REPLY FIELDS
.IP \fIresponse_type\fP 1i
The type of this reply, in this case \fIXCB_RECORD_ENABLE_CONTEXT\fP. This field is also present in the \fIxcb_generic_reply_t\fP and can be used to tell replies apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIlength\fP 1i
The length of the reply, in words (a word is 4 bytes).
.IP \fIcategory\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIelement_header\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIclient_swapped\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIxid_base\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIserver_time\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIrec_sequence_num\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_record_enable_context_cookie_t\fP. Errors have to be handled when calling the reply function \fIxcb_record_enable_context_reply\fP.

If you want to handle errors in the event loop instead, use \fIxcb_record_enable_context_unchecked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from record.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
