.TH xcb_screensaver_set_attributes 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_screensaver_set_attributes \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/screensaver.h>
.SS Request function
.HP
xcb_void_cookie_t \fBxcb_screensaver_set_attributes\fP(xcb_connection_t\ *\fIconn\fP, xcb_drawable_t\ \fIdrawable\fP, int16_t\ \fIx\fP, int16_t\ \fIy\fP, uint16_t\ \fIwidth\fP, uint16_t\ \fIheight\fP, uint16_t\ \fIborder_width\fP, uint8_t\ \fI_class\fP, uint8_t\ \fIdepth\fP, xcb_visualid_t\ \fIvisual\fP, uint32_t\ \fIvalue_mask\fP, const uint32_t\ *\fIvalue_list\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIdrawable\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIx\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIy\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIwidth\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIheight\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIborder_width\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fI_class\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdepth\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIvisual\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIvalue_mask\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIvalue_list\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_void_cookie_t\fP. Errors (if any) have to be handled in the event loop.

If you want to handle errors directly with \fIxcb_request_check\fP instead, use \fIxcb_screensaver_set_attributes_checked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from screensaver.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
