.TH xcb_input_get_device_property 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_input_get_device_property \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xinput.h>
.SS Request function
.HP
xcb_input_get_device_property_cookie_t \fBxcb_input_get_device_property\fP(xcb_connection_t\ *\fIconn\fP, xcb_atom_t\ \fIproperty\fP, xcb_atom_t\ \fItype\fP, uint32_t\ \fIoffset\fP, uint32_t\ \fIlen\fP, uint8_t\ \fIdevice_id\fP, uint8_t\ \fI_delete\fP);
.PP
.SS Reply datastructure
.nf
.sp
typedef struct xcb_input_get_device_property_reply_t {
    uint8_t    \fIresponse_type\fP;
    uint8_t    \fIpad0\fP;
    uint16_t   \fIsequence\fP;
    uint32_t   \fIlength\fP;
    xcb_atom_t \fItype\fP;
    uint32_t   \fIbytes_after\fP;
    uint32_t   \fInum_items\fP;
    uint8_t    \fIformat\fP;
    uint8_t    \fIdevice_id\fP;
    uint8_t    \fIpad1\fP[10];
} \fBxcb_input_get_device_property_reply_t\fP;
.fi
.SS Reply function
.HP
xcb_input_get_device_property_reply_t *\fBxcb_input_get_device_property_reply\fP(xcb_connection_t\ *\fIconn\fP, xcb_input_get_device_property_cookie_t\ \fIcookie\fP, xcb_generic_error_t\ **\fIe\fP);
.SS Reply accessors
xcb_input_get_device_property_items_t *xcb_input_get_device_property_items (const xcb_input_get_device_property_request_t *reply)
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIproperty\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fItype\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIoffset\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIlen\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdevice_id\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fI_delete\fP 1i
TODO: NOT YET DOCUMENTED.
.SH REPLY FIELDS
.IP \fIresponse_type\fP 1i
The type of this reply, in this case \fIXCB_INPUT_GET_DEVICE_PROPERTY\fP. This field is also present in the \fIxcb_generic_reply_t\fP and can be used to tell replies apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIlength\fP 1i
The length of the reply, in words (a word is 4 bytes).
.IP \fItype\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIbytes_after\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fInum_items\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIformat\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdevice_id\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_input_get_device_property_cookie_t\fP. Errors have to be handled when calling the reply function \fIxcb_input_get_device_property_reply\fP.

If you want to handle errors in the event loop instead, use \fIxcb_input_get_device_property_unchecked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from xinput.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
