.TH xcb_xkb_names_notify_event_t 3  "libxcb 1.11" "X Version 11" "XCB Events"
.ad l
.SH NAME
xcb_xkb_names_notify_event_t \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xkb.h>
.PP
.SS Event datastructure
.nf
.sp
typedef struct xcb_xkb_names_notify_event_t {
    uint8_t         \fIresponse_type\fP;
    uint8_t         \fIxkbType\fP;
    uint16_t        \fIsequence\fP;
    xcb_timestamp_t \fItime\fP;
    uint8_t         \fIdeviceID\fP;
    uint8_t         \fIpad0\fP;
    uint16_t        \fIchanged\fP;
    uint8_t         \fIfirstType\fP;
    uint8_t         \fInTypes\fP;
    uint8_t         \fIfirstLevelName\fP;
    uint8_t         \fInLevelNames\fP;
    uint8_t         \fIpad1\fP;
    uint8_t         \fInRadioGroups\fP;
    uint8_t         \fInKeyAliases\fP;
    uint8_t         \fIchangedGroupNames\fP;
    uint16_t        \fIchangedVirtualMods\fP;
    xcb_keycode_t   \fIfirstKey\fP;
    uint8_t         \fInKeys\fP;
    uint32_t        \fIchangedIndicators\fP;
    uint8_t         \fIpad2\fP[4];
} \fBxcb_xkb_names_notify_event_t\fP;
.fi
.br
.hy 1
.SH EVENT FIELDS
.IP \fIresponse_type\fP 1i
The type of this event, in this case \fIXCB_XKB_NAMES_NOTIFY\fP. This field is also present in the \fIxcb_generic_event_t\fP and can be used to tell events apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIxkbType\fP 1i
NOT YET DOCUMENTED.
.IP \fItime\fP 1i
NOT YET DOCUMENTED.
.IP \fIdeviceID\fP 1i
NOT YET DOCUMENTED.
.IP \fIchanged\fP 1i
NOT YET DOCUMENTED.
.IP \fIfirstType\fP 1i
NOT YET DOCUMENTED.
.IP \fInTypes\fP 1i
NOT YET DOCUMENTED.
.IP \fIfirstLevelName\fP 1i
NOT YET DOCUMENTED.
.IP \fInLevelNames\fP 1i
NOT YET DOCUMENTED.
.IP \fInRadioGroups\fP 1i
NOT YET DOCUMENTED.
.IP \fInKeyAliases\fP 1i
NOT YET DOCUMENTED.
.IP \fIchangedGroupNames\fP 1i
NOT YET DOCUMENTED.
.IP \fIchangedVirtualMods\fP 1i
NOT YET DOCUMENTED.
.IP \fIfirstKey\fP 1i
NOT YET DOCUMENTED.
.IP \fInKeys\fP 1i
NOT YET DOCUMENTED.
.IP \fIchangedIndicators\fP 1i
NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH SEE ALSO
.SH AUTHOR
Generated from xkb.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
