.TH xcb_glx_pbuffer_clobber_event_t 3  "libxcb 1.11" "X Version 11" "XCB Events"
.ad l
.SH NAME
xcb_glx_pbuffer_clobber_event_t \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/glx.h>
.PP
.SS Event datastructure
.nf
.sp
typedef struct xcb_glx_pbuffer_clobber_event_t {
    uint8_t            \fIresponse_type\fP;
    uint8_t            \fIpad0\fP;
    uint16_t           \fIsequence\fP;
    uint16_t           \fIevent_type\fP;
    uint16_t           \fIdraw_type\fP;
    xcb_glx_drawable_t \fIdrawable\fP;
    uint32_t           \fIb_mask\fP;
    uint16_t           \fIaux_buffer\fP;
    uint16_t           \fIx\fP;
    uint16_t           \fIy\fP;
    uint16_t           \fIwidth\fP;
    uint16_t           \fIheight\fP;
    uint16_t           \fIcount\fP;
    uint8_t            \fIpad1\fP[4];
} \fBxcb_glx_pbuffer_clobber_event_t\fP;
.fi
.br
.hy 1
.SH EVENT FIELDS
.IP \fIresponse_type\fP 1i
The type of this event, in this case \fIXCB_GLX_PBUFFER_CLOBBER\fP. This field is also present in the \fIxcb_generic_event_t\fP and can be used to tell events apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIevent_type\fP 1i
NOT YET DOCUMENTED.
.IP \fIdraw_type\fP 1i
NOT YET DOCUMENTED.
.IP \fIdrawable\fP 1i
NOT YET DOCUMENTED.
.IP \fIb_mask\fP 1i
NOT YET DOCUMENTED.
.IP \fIaux_buffer\fP 1i
NOT YET DOCUMENTED.
.IP \fIx\fP 1i
NOT YET DOCUMENTED.
.IP \fIy\fP 1i
NOT YET DOCUMENTED.
.IP \fIwidth\fP 1i
NOT YET DOCUMENTED.
.IP \fIheight\fP 1i
NOT YET DOCUMENTED.
.IP \fIcount\fP 1i
NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH SEE ALSO
.SH AUTHOR
Generated from glx.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
