.TH xcb_query_colors 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_query_colors \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xproto.h>
.SS Request function
.HP
xcb_query_colors_cookie_t \fBxcb_query_colors\fP(xcb_connection_t\ *\fIconn\fP, xcb_colormap_t\ \fIcmap\fP, uint32_t\ \fIpixels_len\fP, const uint32_t\ *\fIpixels\fP);
.PP
.SS Reply datastructure
.nf
.sp
typedef struct xcb_query_colors_reply_t {
    uint8_t  \fIresponse_type\fP;
    uint8_t  \fIpad0\fP;
    uint16_t \fIsequence\fP;
    uint32_t \fIlength\fP;
    uint16_t \fIcolors_len\fP;
    uint8_t  \fIpad1\fP[22];
} \fBxcb_query_colors_reply_t\fP;
.fi
.SS Reply function
.HP
xcb_query_colors_reply_t *\fBxcb_query_colors_reply\fP(xcb_connection_t\ *\fIconn\fP, xcb_query_colors_cookie_t\ \fIcookie\fP, xcb_generic_error_t\ **\fIe\fP);
.SS Reply accessors
.HP
xcb_rgb_t *\fBxcb_query_colors_colors\fP(const xcb_query_colors_request_t *\fIreply\fP);
.HP
int \fBxcb_query_colors_colors_length\fP(const xcb_query_colors_reply_t *\fIreply\fP);
.HP
xcb_rgb_iterator_t \fBxcb_query_colors_colors_iterator\fP(const xcb_query_colors_reply_t *\fIreply\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIcmap\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIpixels_len\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIpixels\fP 1i
TODO: NOT YET DOCUMENTED.
.SH REPLY FIELDS
.IP \fIresponse_type\fP 1i
The type of this reply, in this case \fIXCB_QUERY_COLORS\fP. This field is also present in the \fIxcb_generic_reply_t\fP and can be used to tell replies apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIlength\fP 1i
The length of the reply, in words (a word is 4 bytes).
.IP \fIcolors_len\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_query_colors_cookie_t\fP. Errors have to be handled when calling the reply function \fIxcb_query_colors_reply\fP.

If you want to handle errors in the event loop instead, use \fIxcb_query_colors_unchecked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from xproto.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
