.TH xcb_render_query_pict_formats 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_render_query_pict_formats \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/render.h>
.SS Request function
.HP
xcb_render_query_pict_formats_cookie_t \fBxcb_render_query_pict_formats\fP(xcb_connection_t\ *\fIconn\fP, 
.PP
.SS Reply datastructure
.nf
.sp
typedef struct xcb_render_query_pict_formats_reply_t {
    uint8_t  \fIresponse_type\fP;
    uint8_t  \fIpad0\fP;
    uint16_t \fIsequence\fP;
    uint32_t \fIlength\fP;
    uint32_t \fInum_formats\fP;
    uint32_t \fInum_screens\fP;
    uint32_t \fInum_depths\fP;
    uint32_t \fInum_visuals\fP;
    uint32_t \fInum_subpixel\fP;
    uint8_t  \fIpad1\fP[4];
} \fBxcb_render_query_pict_formats_reply_t\fP;
.fi
.SS Reply function
.HP
xcb_render_query_pict_formats_reply_t *\fBxcb_render_query_pict_formats_reply\fP(xcb_connection_t\ *\fIconn\fP, xcb_render_query_pict_formats_cookie_t\ \fIcookie\fP, xcb_generic_error_t\ **\fIe\fP);
.SS Reply accessors
.HP
xcb_render_pictforminfo_t *\fBxcb_render_query_pict_formats_formats\fP(const xcb_render_query_pict_formats_request_t *\fIreply\fP);
.HP
int \fBxcb_render_query_pict_formats_formats_length\fP(const xcb_render_query_pict_formats_reply_t *\fIreply\fP);
.HP
xcb_render_pictforminfo_iterator_t \fBxcb_render_query_pict_formats_formats_iterator\fP(const xcb_render_query_pict_formats_reply_t *\fIreply\fP);
.HP
int \fBxcb_render_query_pict_formats_screens_length\fP(const xcb_render_query_pict_formats_reply_t *\fIreply\fP);
.HP
xcb_render_pictscreen_iterator_t \fBxcb_render_query_pict_formats_screens_iterator\fP(const xcb_render_query_pict_formats_reply_t *\fIreply\fP);
.HP
uint32_t *\fBxcb_render_query_pict_formats_subpixels\fP(const xcb_render_query_pict_formats_request_t *\fIreply\fP);
.HP
int \fBxcb_render_query_pict_formats_subpixels_length\fP(const xcb_render_query_pict_formats_reply_t *\fIreply\fP);
.HP
xcb_generic_iterator_t \fBxcb_render_query_pict_formats_subpixels_end\fP(const xcb_render_query_pict_formats_reply_t *\fIreply\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.SH REPLY FIELDS
.IP \fIresponse_type\fP 1i
The type of this reply, in this case \fIXCB_RENDER_QUERY_PICT_FORMATS\fP. This field is also present in the \fIxcb_generic_reply_t\fP and can be used to tell replies apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIlength\fP 1i
The length of the reply, in words (a word is 4 bytes).
.IP \fInum_formats\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fInum_screens\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fInum_depths\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fInum_visuals\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fInum_subpixel\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_render_query_pict_formats_cookie_t\fP. Errors have to be handled when calling the reply function \fIxcb_render_query_pict_formats_reply\fP.

If you want to handle errors in the event loop instead, use \fIxcb_render_query_pict_formats_unchecked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from render.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
