.TH xcb_put_image 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_put_image \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xproto.h>
.SS Request function
.HP
xcb_void_cookie_t \fBxcb_put_image\fP(xcb_connection_t\ *\fIconn\fP, uint8_t\ \fIformat\fP, xcb_drawable_t\ \fIdrawable\fP, xcb_gcontext_t\ \fIgc\fP, uint16_t\ \fIwidth\fP, uint16_t\ \fIheight\fP, int16_t\ \fIdst_x\fP, int16_t\ \fIdst_y\fP, uint8_t\ \fIleft_pad\fP, uint8_t\ \fIdepth\fP, uint32_t\ \fIdata_len\fP, const uint8_t\ *\fIdata\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIformat\fP 1i
One of the following values:
.RS 1i
.IP \fIXCB_IMAGE_FORMAT_XY_BITMAP\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_IMAGE_FORMAT_XY_PIXMAP\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_IMAGE_FORMAT_Z_PIXMAP\fP 1i
TODO: NOT YET DOCUMENTED.
.RE
.RS 1i
TODO: NOT YET DOCUMENTED.
.RE
.IP \fIdrawable\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIgc\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIwidth\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIheight\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdst_x\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdst_y\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIleft_pad\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdepth\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdata_len\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdata\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_void_cookie_t\fP. Errors (if any) have to be handled in the event loop.

If you want to handle errors directly with \fIxcb_request_check\fP instead, use \fIxcb_put_image_checked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from xproto.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
