.TH xcb_selinux_get_selection_create_context 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_selinux_get_selection_create_context \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xselinux.h>
.SS Request function
.HP
xcb_selinux_get_selection_create_context_cookie_t \fBxcb_selinux_get_selection_create_context\fP(xcb_connection_t\ *\fIconn\fP, 
.PP
.SS Reply datastructure
.nf
.sp
typedef struct xcb_selinux_get_selection_create_context_reply_t {
    uint8_t  \fIresponse_type\fP;
    uint8_t  \fIpad0\fP;
    uint16_t \fIsequence\fP;
    uint32_t \fIlength\fP;
    uint32_t \fIcontext_len\fP;
    uint8_t  \fIpad1\fP[20];
} \fBxcb_selinux_get_selection_create_context_reply_t\fP;
.fi
.SS Reply function
.HP
xcb_selinux_get_selection_create_context_reply_t *\fBxcb_selinux_get_selection_create_context_reply\fP(xcb_connection_t\ *\fIconn\fP, xcb_selinux_get_selection_create_context_cookie_t\ \fIcookie\fP, xcb_generic_error_t\ **\fIe\fP);
.SS Reply accessors
.HP
char *\fBxcb_selinux_get_selection_create_context_context\fP(const xcb_selinux_get_selection_create_context_request_t *\fIreply\fP);
.HP
int \fBxcb_selinux_get_selection_create_context_context_length\fP(const xcb_selinux_get_selection_create_context_reply_t *\fIreply\fP);
.HP
xcb_generic_iterator_t \fBxcb_selinux_get_selection_create_context_context_end\fP(const xcb_selinux_get_selection_create_context_reply_t *\fIreply\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.SH REPLY FIELDS
.IP \fIresponse_type\fP 1i
The type of this reply, in this case \fIXCB_SELINUX_GET_SELECTION_CREATE_CONTEXT\fP. This field is also present in the \fIxcb_generic_reply_t\fP and can be used to tell replies apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIlength\fP 1i
The length of the reply, in words (a word is 4 bytes).
.IP \fIcontext_len\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_selinux_get_selection_create_context_cookie_t\fP. Errors have to be handled when calling the reply function \fIxcb_selinux_get_selection_create_context_reply\fP.

If you want to handle errors in the event loop instead, use \fIxcb_selinux_get_selection_create_context_unchecked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from xselinux.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
