.TH xcb_fill_poly 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_fill_poly \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xproto.h>
.SS Request function
.HP
xcb_void_cookie_t \fBxcb_fill_poly\fP(xcb_connection_t\ *\fIconn\fP, xcb_drawable_t\ \fIdrawable\fP, xcb_gcontext_t\ \fIgc\fP, uint8_t\ \fIshape\fP, uint8_t\ \fIcoordinate_mode\fP, uint32_t\ \fIpoints_len\fP, const xcb_point_t\ *\fIpoints\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIdrawable\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIgc\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIshape\fP 1i
One of the following values:
.RS 1i
.IP \fIXCB_POLY_SHAPE_COMPLEX\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_POLY_SHAPE_NONCONVEX\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIXCB_POLY_SHAPE_CONVEX\fP 1i
TODO: NOT YET DOCUMENTED.
.RE
.RS 1i
TODO: NOT YET DOCUMENTED.
.RE
.IP \fIcoordinate_mode\fP 1i
One of the following values:
.RS 1i
.IP \fIXCB_COORD_MODE_ORIGIN\fP 1i
Treats all coordinates as relative to the origin.
.IP \fIXCB_COORD_MODE_PREVIOUS\fP 1i
Treats all coordinates after the first as relative to the previous coordinate.
.RE
.RS 1i
TODO: NOT YET DOCUMENTED.
.RE
.IP \fIpoints_len\fP 1i
One of the following values:
.RS 1i
.IP \fIXCB_COORD_MODE_ORIGIN\fP 1i
Treats all coordinates as relative to the origin.
.IP \fIXCB_COORD_MODE_PREVIOUS\fP 1i
Treats all coordinates after the first as relative to the previous coordinate.
.RE
.RS 1i
TODO: NOT YET DOCUMENTED.
.RE
.IP \fIpoints\fP 1i
One of the following values:
.RS 1i
.IP \fIXCB_COORD_MODE_ORIGIN\fP 1i
Treats all coordinates as relative to the origin.
.IP \fIXCB_COORD_MODE_PREVIOUS\fP 1i
Treats all coordinates after the first as relative to the previous coordinate.
.RE
.RS 1i
TODO: NOT YET DOCUMENTED.
.RE
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_void_cookie_t\fP. Errors (if any) have to be handled in the event loop.

If you want to handle errors directly with \fIxcb_request_check\fP instead, use \fIxcb_fill_poly_checked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from xproto.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
