.TH xcb_test_get_version 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_test_get_version \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xtest.h>
.SS Request function
.HP
xcb_test_get_version_cookie_t \fBxcb_test_get_version\fP(xcb_connection_t\ *\fIconn\fP, uint8_t\ \fImajor_version\fP, uint16_t\ \fIminor_version\fP);
.PP
.SS Reply datastructure
.nf
.sp
typedef struct xcb_test_get_version_reply_t {
    uint8_t  \fIresponse_type\fP;
    uint8_t  \fImajor_version\fP;
    uint16_t \fIsequence\fP;
    uint32_t \fIlength\fP;
    uint16_t \fIminor_version\fP;
} \fBxcb_test_get_version_reply_t\fP;
.fi
.SS Reply function
.HP
xcb_test_get_version_reply_t *\fBxcb_test_get_version_reply\fP(xcb_connection_t\ *\fIconn\fP, xcb_test_get_version_cookie_t\ \fIcookie\fP, xcb_generic_error_t\ **\fIe\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fImajor_version\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIminor_version\fP 1i
TODO: NOT YET DOCUMENTED.
.SH REPLY FIELDS
.IP \fIresponse_type\fP 1i
The type of this reply, in this case \fIXCB_TEST_GET_VERSION\fP. This field is also present in the \fIxcb_generic_reply_t\fP and can be used to tell replies apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIlength\fP 1i
The length of the reply, in words (a word is 4 bytes).
.IP \fImajor_version\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIminor_version\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_test_get_version_cookie_t\fP. Errors have to be handled when calling the reply function \fIxcb_test_get_version_reply\fP.

If you want to handle errors in the event loop instead, use \fIxcb_test_get_version_unchecked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from xtest.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
