.TH xcb_warp_pointer 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_warp_pointer \- move mouse pointer
.SH SYNOPSIS
.hy 0
.B #include <xcb/xproto.h>
.SS Request function
.HP
xcb_void_cookie_t \fBxcb_warp_pointer\fP(xcb_connection_t\ *\fIconn\fP, xcb_window_t\ \fIsrc_window\fP, xcb_window_t\ \fIdst_window\fP, int16_t\ \fIsrc_x\fP, int16_t\ \fIsrc_y\fP, uint16_t\ \fIsrc_width\fP, uint16_t\ \fIsrc_height\fP, int16_t\ \fIdst_x\fP, int16_t\ \fIdst_y\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIsrc_window\fP 1i
If \fIsrc_window\fP is not \fIXCB_NONE\fP (TODO), the move will only take place if the
pointer is inside \fIsrc_window\fP and within the rectangle specified by (\fIsrc_x\fP,
\fIsrc_y\fP, \fIsrc_width\fP, \fIsrc_height\fP). The rectangle coordinates are relative to
\fIsrc_window\fP.
.IP \fIdst_window\fP 1i
If \fIdst_window\fP is not \fIXCB_NONE\fP (TODO), the pointer will be moved to the
offsets (\fIdst_x\fP, \fIdst_y\fP) relative to \fIdst_window\fP. If \fIdst_window\fP is
\fIXCB_NONE\fP (TODO), the pointer will be moved by the offsets (\fIdst_x\fP, \fIdst_y\fP)
relative to the current position of the pointer.
.IP \fIsrc_x\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIsrc_y\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIsrc_width\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIsrc_height\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdst_x\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdst_y\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
Moves the mouse pointer to the specified position.

If \fIsrc_window\fP is not \fIXCB_NONE\fP (TODO), the move will only take place if the
pointer is inside \fIsrc_window\fP and within the rectangle specified by (\fIsrc_x\fP,
\fIsrc_y\fP, \fIsrc_width\fP, \fIsrc_height\fP). The rectangle coordinates are relative to
\fIsrc_window\fP.

If \fIdst_window\fP is not \fIXCB_NONE\fP (TODO), the pointer will be moved to the
offsets (\fIdst_x\fP, \fIdst_y\fP) relative to \fIdst_window\fP. If \fIdst_window\fP is
\fIXCB_NONE\fP (TODO), the pointer will be moved by the offsets (\fIdst_x\fP, \fIdst_y\fP)
relative to the current position of the pointer.
.SH RETURN VALUE
Returns an \fIxcb_void_cookie_t\fP. Errors (if any) have to be handled in the event loop.

If you want to handle errors directly with \fIxcb_request_check\fP instead, use \fIxcb_warp_pointer_checked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
.IP \fIxcb_window_error_t\fP 1i
TODO: reasons?
.SH SEE ALSO
.BR xcb-requests (3),
.BR xcb_set_input_focus (3)
.SH AUTHOR
Generated from xproto.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
