.TH xcb_xkb_set_names 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_xkb_set_names \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xkb.h>
.SS Request function
.HP
xcb_void_cookie_t \fBxcb_xkb_set_names\fP(xcb_connection_t\ *\fIconn\fP, xcb_xkb_device_spec_t\ \fIdeviceSpec\fP, uint16_t\ \fIvirtualMods\fP, uint32_t\ \fIwhich\fP, uint8_t\ \fIfirstType\fP, uint8_t\ \fInTypes\fP, uint8_t\ \fIfirstKTLevelt\fP, uint8_t\ \fInKTLevels\fP, uint32_t\ \fIindicators\fP, uint8_t\ \fIgroupNames\fP, uint8_t\ \fInRadioGroups\fP, xcb_keycode_t\ \fIfirstKey\fP, uint8_t\ \fInKeys\fP, uint8_t\ \fInKeyAliases\fP, uint16_t\ \fItotalKTLevelNames\fP, const void\ *\fIvalues\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIdeviceSpec\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIvirtualMods\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIwhich\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIfirstType\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fInTypes\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIfirstKTLevelt\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fInKTLevels\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIindicators\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIgroupNames\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fInRadioGroups\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIfirstKey\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fInKeys\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fInKeyAliases\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fItotalKTLevelNames\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIvalues\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_void_cookie_t\fP. Errors (if any) have to be handled in the event loop.

If you want to handle errors directly with \fIxcb_request_check\fP instead, use \fIxcb_xkb_set_names_checked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from xkb.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
