.TH xcb_xkb_set_map 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_xkb_set_map \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xkb.h>
.SS Request function
.HP
xcb_void_cookie_t \fBxcb_xkb_set_map\fP(xcb_connection_t\ *\fIconn\fP, xcb_xkb_device_spec_t\ \fIdeviceSpec\fP, uint16_t\ \fIpresent\fP, uint16_t\ \fIflags\fP, xcb_keycode_t\ \fIminKeyCode\fP, xcb_keycode_t\ \fImaxKeyCode\fP, uint8_t\ \fIfirstType\fP, uint8_t\ \fInTypes\fP, xcb_keycode_t\ \fIfirstKeySym\fP, uint8_t\ \fInKeySyms\fP, uint16_t\ \fItotalSyms\fP, xcb_keycode_t\ \fIfirstKeyAction\fP, uint8_t\ \fInKeyActions\fP, uint16_t\ \fItotalActions\fP, xcb_keycode_t\ \fIfirstKeyBehavior\fP, uint8_t\ \fInKeyBehaviors\fP, uint8_t\ \fItotalKeyBehaviors\fP, xcb_keycode_t\ \fIfirstKeyExplicit\fP, uint8_t\ \fInKeyExplicit\fP, uint8_t\ \fItotalKeyExplicit\fP, xcb_keycode_t\ \fIfirstModMapKey\fP, uint8_t\ \fInModMapKeys\fP, uint8_t\ \fItotalModMapKeys\fP, xcb_keycode_t\ \fIfirstVModMapKey\fP, uint8_t\ \fInVModMapKeys\fP, uint8_t\ \fItotalVModMapKeys\fP, uint16_t\ \fIvirtualMods\fP, const void\ *\fIvalues\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIdeviceSpec\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIpresent\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIflags\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIminKeyCode\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fImaxKeyCode\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIfirstType\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fInTypes\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIfirstKeySym\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fInKeySyms\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fItotalSyms\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIfirstKeyAction\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fInKeyActions\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fItotalActions\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIfirstKeyBehavior\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fInKeyBehaviors\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fItotalKeyBehaviors\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIfirstKeyExplicit\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fInKeyExplicit\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fItotalKeyExplicit\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIfirstModMapKey\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fInModMapKeys\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fItotalModMapKeys\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIfirstVModMapKey\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fInVModMapKeys\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fItotalVModMapKeys\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIvirtualMods\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIvalues\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_void_cookie_t\fP. Errors (if any) have to be handled in the event loop.

If you want to handle errors directly with \fIxcb_request_check\fP instead, use \fIxcb_xkb_set_map_checked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from xkb.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
