.TH xcb_xv_put_image 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_xv_put_image \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xv.h>
.SS Request function
.HP
xcb_void_cookie_t \fBxcb_xv_put_image\fP(xcb_connection_t\ *\fIconn\fP, xcb_xv_port_t\ \fIport\fP, xcb_drawable_t\ \fIdrawable\fP, xcb_gcontext_t\ \fIgc\fP, uint32_t\ \fIid\fP, int16_t\ \fIsrc_x\fP, int16_t\ \fIsrc_y\fP, uint16_t\ \fIsrc_w\fP, uint16_t\ \fIsrc_h\fP, int16_t\ \fIdrw_x\fP, int16_t\ \fIdrw_y\fP, uint16_t\ \fIdrw_w\fP, uint16_t\ \fIdrw_h\fP, uint16_t\ \fIwidth\fP, uint16_t\ \fIheight\fP, uint32_t\ \fIdata_len\fP, const uint8_t\ *\fIdata\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIport\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdrawable\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIgc\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIid\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIsrc_x\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIsrc_y\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIsrc_w\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIsrc_h\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdrw_x\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdrw_y\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdrw_w\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdrw_h\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIwidth\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIheight\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdata_len\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIdata\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_void_cookie_t\fP. Errors (if any) have to be handled in the event loop.

If you want to handle errors directly with \fIxcb_request_check\fP instead, use \fIxcb_xv_put_image_checked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from xv.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
