.TH xcb_get_motion_events 3  "libxcb 1.11" "X Version 11" "XCB Requests"
.ad l
.SH NAME
xcb_get_motion_events \- 
.SH SYNOPSIS
.hy 0
.B #include <xcb/xproto.h>
.SS Request function
.HP
xcb_get_motion_events_cookie_t \fBxcb_get_motion_events\fP(xcb_connection_t\ *\fIconn\fP, xcb_window_t\ \fIwindow\fP, xcb_timestamp_t\ \fIstart\fP, xcb_timestamp_t\ \fIstop\fP);
.PP
.SS Reply datastructure
.nf
.sp
typedef struct xcb_get_motion_events_reply_t {
    uint8_t  \fIresponse_type\fP;
    uint8_t  \fIpad0\fP;
    uint16_t \fIsequence\fP;
    uint32_t \fIlength\fP;
    uint32_t \fIevents_len\fP;
    uint8_t  \fIpad1\fP[20];
} \fBxcb_get_motion_events_reply_t\fP;
.fi
.SS Reply function
.HP
xcb_get_motion_events_reply_t *\fBxcb_get_motion_events_reply\fP(xcb_connection_t\ *\fIconn\fP, xcb_get_motion_events_cookie_t\ \fIcookie\fP, xcb_generic_error_t\ **\fIe\fP);
.SS Reply accessors
.HP
xcb_timecoord_t *\fBxcb_get_motion_events_events\fP(const xcb_get_motion_events_request_t *\fIreply\fP);
.HP
int \fBxcb_get_motion_events_events_length\fP(const xcb_get_motion_events_reply_t *\fIreply\fP);
.HP
xcb_timecoord_iterator_t \fBxcb_get_motion_events_events_iterator\fP(const xcb_get_motion_events_reply_t *\fIreply\fP);
.br
.hy 1
.SH REQUEST ARGUMENTS
.IP \fIconn\fP 1i
The XCB connection to X11.
.IP \fIwindow\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIstart\fP 1i
TODO: NOT YET DOCUMENTED.
.IP \fIstop\fP 1i
TODO: NOT YET DOCUMENTED.
.SH REPLY FIELDS
.IP \fIresponse_type\fP 1i
The type of this reply, in this case \fIXCB_GET_MOTION_EVENTS\fP. This field is also present in the \fIxcb_generic_reply_t\fP and can be used to tell replies apart from each other.
.IP \fIsequence\fP 1i
The sequence number of the last request processed by the X11 server.
.IP \fIlength\fP 1i
The length of the reply, in words (a word is 4 bytes).
.IP \fIevents_len\fP 1i
TODO: NOT YET DOCUMENTED.
.SH DESCRIPTION
.SH RETURN VALUE
Returns an \fIxcb_get_motion_events_cookie_t\fP. Errors have to be handled when calling the reply function \fIxcb_get_motion_events_reply\fP.

If you want to handle errors in the event loop instead, use \fIxcb_get_motion_events_unchecked\fP. See \fBxcb-requests(3)\fP for details.
.SH ERRORS
This request does never generate any errors.
.SH SEE ALSO
.SH AUTHOR
Generated from xproto.xml. Contact xcb@lists.freedesktop.org for corrections and improvements.
