#!/bin/sh
DIALOG=Xdialog

(
echo "10" ; sleep 1
echo "XXX" ; echo "The new" ; echo "\\n" ; echo "message"; echo "XXX"
echo "20" ; sleep 1
echo "50" ; sleep 1
echo "75" ; sleep 1
echo "100" ; sleep 1
) |
$DIALOG --title "GAUGE" --gauge "Hi, this is a gauge widget" 8 30

if [ "$?" = 255 ] ; then
	echo ""
	echo "Box closed !"
fi
