include /source/fbpanel/fbpanel-5.6/config.mk

SRCS = main.c fixedtip.c eggtraymanager.c egg-marshal.c 
LIBTARGET = tray.so
install:
	$(install) 755 $(LIBDIR)/fbpanel 755 $(LIBTARGET)

include /source/fbpanel/fbpanel-5.6/rules.mk
