#!/bin/sh

./configure --prefix=/15 --x-includes=/usr/xorg/include --x-libraries=/usr/xorg/lib \
--enable-gl=no --enable-shared --disable-largefile --enable-localjpeg=no --enable-localzlib=no \
--enable-localpng=no
