.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH TSENG 4 "xf86-video-tseng 1.2.5" "X Version 11"
.SH NAME
tseng \- Tseng Labs video driver
.SH SYNOPSIS
.nf
.B "Section \*qDevice\*q"
.BI "  Identifier \*q"  devname \*q
.B  "  Driver \*qtseng\*q"
\ \ ...
.B EndSection
.fi
.SH DESCRIPTION
.B tseng 
is an Xorg driver for Tseng Labs video cards.
THIS MAN PAGE NEEDS TO BE FILLED IN.
.SH SUPPORTED HARDWARE
The
.B tseng
driver supports...
.SH CONFIGURATION DETAILS
Please refer to xorg.conf(5) for general configuration
details.  This section only covers configuration details specific to this
driver.
.SH "SEE ALSO"
Xorg(1), xorg.conf(5), Xserver(1), X(7)
.SH AUTHORS
Authors include: ...
