#!/bin/sh

glib_libs="-L/usr/lib -rdynamic -lgmodule -lglib -ldl"
glib_cflags="-I/usr/lib/glib/include"
glib_thread_libs="-L/usr/lib -rdynamic -lgmodule -lgthread -lglib -lpthread -ldl"
glib_thread_cflags="-I/usr/lib/glib/include -D_REENTRANT"

prefix=/usr
exec_prefix=${prefix}
exec_prefix_set=no

usage()
{
	cat <<EOF
Usage: gtk-config [OPTIONS] [LIBRARIES]
Options:
	[--prefix[=DIR]]
	[--exec-prefix[=DIR]]
	[--version]
	[--libs]
	[--cflags]
Libraries:
	gtk
	gthread
EOF
	exit $1
}

if test $# -eq 0; then
	usage 1 1>&2
fi

lib_gtk=yes

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo_prefix=yes
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo_exec_prefix=yes
      ;;
    --version)
      echo 1.2.0
      ;;
    --cflags)
      echo_cflags=yes
      ;;
    --libs)
      echo_libs=yes
      ;;
    gtk)
      lib_gtk=yes
      ;;
    gthread)
      lib_gthread=yes
      ;;
    *)
      usage 1 1>&2
      ;;
  esac
  shift
done

if test "$echo_prefix" = "yes"; then
	echo $prefix
fi

if test "$echo_exec_prefix" = "yes"; then
	echo $exec_prefix
fi

if test "$lib_gthread" = "yes"; then
      glib_cflags="$glib_thread_cflags"
      glib_libs="$glib_thread_libs"
fi

if test "$echo_cflags" = "yes"; then
      if test ${prefix}/include != /usr/include ; then
        includes=-I${prefix}/include
        for i in $glib_cflags ; do
          if test $i = -I${prefix}/include ; then
            includes=""
          fi
        done
      fi
      echo $includes  -I/usr/xorg/include/ $glib_cflags
fi

if test "$echo_libs" = "yes"; then
      my_glib_libs=
      libdirs=-L${exec_prefix}/lib
      for i in $glib_libs ; do
        if test $i != -L${exec_prefix}/lib ; then
          if test -z "$my_glib_libs" ; then
            my_glib_libs="$i"
          else
            my_glib_libs="$my_glib_libs $i"
          fi
        fi
      done

      echo $libdirs   -L/usr/xorg/lib -lgtk -lgdk $my_glib_libs  -lXext -lX11   -lm
fi      

