#!/bin/sh

test "$ACTION" = "add" || exit 0
test -n "$DEVNAME" || exit 0 
test -e "/usr/var/run/openct/status" || exit 0

if [ -n "$DEVNAME" ]
then
	/usr/sbin/openct-control attach ccid serial $DEVNAME
	exit 0
fi
