#! /bin/sh

. /etc/ponix.global

case "$1" in  
init)
    if ! pkg_initialized $PACKAGE; then

	/bin/tsol_initsound.sh
	
	pkg_set_init_flag $PACKAGE
    fi
    ;;
help)
    echo "Usage: $0 init"
    ;;
  *)
    exit 1
    ;;
esac

exit 0
