#! /bin/sh

. $TS_GLOBAL

case "$1" in  
init)
	if [ -n "$LOG_DELAY" ] ; then
		echo_log "Running delayed log. Delay=$LOG_DELAY"
		(sleep $LOG_DELAY && /bin/loger)&
	fi

    ;;
help)
    echo "Usage: $0 init"
    ;;
  *)
    exit 1
    ;;
esac

exit 0
