#! /bin/sh

. $TS_GLOBAL

case "$1" in  
init)
        if [ -n "$NTP_SERVER" ]; then
                        /bin/ntpd -q -p $NTP_SERVER
        fi
    ;;
help)
    echo "Usage: $0 init"
    ;;
  *)
    exit 1
    ;;
esac

exit 0
