.TH xaumix 1 "1999/10/08" Linux "user commands"

.SH NAME
xaumix \- aumix wrapper for X

.SH DESCRIPTION
.I xaumix
is a wrapper to select one of rxvt, xterm, kterm, or one of the other possible
xterm "clones", and to launch that with aumix running in it. For some X
terminal emulators an aumix colour scheme file is used to generate a sensible
display (for example, rxvt and xterm behave differently with respect to the
handling of colours).

This script was originally intended for use from the Debian
.B menu
system, but may also be invoked manually from a shell.
The GTK+ interface to
.I aumix
largely supercedes it.

.SH AUTHOR
Paul Slootman <paul@debian.org>, originally called aumix-X-wrapper.
.br

.SH SEE ALSO
.BR aumix (1), 
.BR xterm (1x),
.BR rxvt (1),
.BR eterm (1),
.BR kterm (1),
.BR wterm (1),
.BR xvt (1)
