.ds q \N'34'
.TH TRANSSET __appmansuffix__ __xorgversion__
.SH NAME
transset \- Set transparency on a window
.SH SYNOPSIS
.BI "transset [\-d " display "] n
.SH DESCRIPTION
.B transset
is a simple program for X servers supporting the XFIXES, DAMAGE,
and COMPOSITE extensions.  It lets the user set the transparency on a window.
.SH OPTIONS
.TP
.BI n
Where n is a number from 0 to 1, zero being transparent and 1 being opaque
.SH BUGS
Probably.  Please report any you find to https://bugs.freedesktop.org/enter_bug.cgi?product=xorg.
.SH AUTHORS
Matthew Hawn
