# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /6
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/gtk+
pkglibdir = $(libdir)/gtk+
pkgincludedir = $(includedir)/gtk+

top_builddir = ..

ACLOCAL = aclocal 
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
AS = @AS@
AWK = gawk
CATALOGS =  az.gmo ca.gmo cs.gmo da.gmo de.gmo el.gmo es.gmo et.gmo eu.gmo fi.gmo fr.gmo ga.gmo gl.gmo hr.gmo hu.gmo it.gmo ja.gmo ko.gmo lt.gmo nl.gmo no.gmo nn.gmo pl.gmo pt.gmo pt_BR.gmo ro.gmo ru.gmo sk.gmo sl.gmo sp.gmo sr.gmo sv.gmo tr.gmo uk.gmo vi.gmo wa.gmo zh_CN.GB2312.gmo zh_TW.Big5.gmo
CATOBJEXT = .gmo
CC = i486-TSOL-linux-gnu-gcc
DATADIRNAME = share
DLLTOOL = @DLLTOOL@
GDK_WLIBS = 
GENCAT = 
GLIB_CFLAGS = -I/usr/lib/glib/include -D_REENTRANT
GLIB_CONFIG = /usr/bin/glib-config
GLIB_DEPLIBS = -L/usr/lib -rdynamic -lgmodule -lglib -ldl
GLIB_LIBS = -L/usr/lib -rdynamic -lgmodule -lglib -ldl
GMOFILES =  az.gmo ca.gmo cs.gmo da.gmo de.gmo el.gmo es.gmo et.gmo eu.gmo fi.gmo fr.gmo ga.gmo gl.gmo hr.gmo hu.gmo it.gmo ja.gmo ko.gmo lt.gmo nl.gmo no.gmo nn.gmo pl.gmo pt.gmo pt_BR.gmo ro.gmo ru.gmo sk.gmo sl.gmo sp.gmo sr.gmo sv.gmo tr.gmo uk.gmo vi.gmo wa.gmo zh_CN.GB2312.gmo zh_TW.Big5.gmo
GMSGFMT = /usr/bin/msgfmt
GTK_BINARY_AGE = 10
GTK_DEBUG_FLAGS = -DG_ENABLE_DEBUG
GTK_INTERFACE_AGE = 1
GTK_LOCALE_FLAGS = 
GTK_MAJOR_VERSION = 1
GTK_MICRO_VERSION = 10
GTK_MINOR_VERSION = 2
GTK_VERSION = 1.2.10
GTK_XIM_FLAGS = -DUSE_XIM
GT_NO = 
GT_YES = #YES#
INCLUDE_LOCALE_H = #include <locale.h>
INDENT = 
INSTOBJEXT = .mo
INTLDEPS = 
INTLLIBS = 
INTLOBJS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LT_AGE = 9
LT_CURRENT = 9
LT_RELEASE = 1.2
LT_REVISION = 1
MAINT = #
MAKEINFO = /source/gtk/1.2.0/gtk+-1.2.10/missing makeinfo
MKINSTALLDIRS = ./mkinstalldirs
OBJDUMP = @OBJDUMP@
PACKAGE = gtk+
PERL = perl
POFILES =  az.po ca.po cs.po da.po de.po el.po es.po et.po eu.po fi.po fr.po ga.po gl.po hr.po hu.po it.po ja.po ko.po lt.po nl.po no.po nn.po pl.po pt.po pt_BR.po ro.po ru.po sk.po sl.po sp.po sr.po sv.po tr.po uk.po vi.po wa.po zh_CN.GB2312.po zh_TW.Big5.po
POSUB = po
RANLIB = ranlib
REBUILD = 
STRIP_BEGIN = $(strip $(STRIP_DUMMY)
STRIP_DUMMY = 
STRIP_END = )
USE_INCLUDED_LIBINTL = no
USE_NLS = yes
VERSION = 1.2.10
glib_cflags = -I/usr/lib/glib/include
glib_libs = -L/usr/lib -rdynamic -lgmodule -lglib -ldl
glib_thread_cflags = -I/usr/lib/glib/include -D_REENTRANT
glib_thread_libs = -L/usr/lib -rdynamic -lgmodule -lgthread -lglib -lpthread -ldl
gtklocaledir = ${prefix}/${DATADIRNAME}/locale
l = 
x_cflags =  -I/usr/xorg/include/
x_includes = /usr/xorg/include/
x_ldflags =   -L/usr/xorg/lib
x_libs = -lXext -lX11 
xinput_progs = 

INCLUDES = $(strip $(STRIP_DUMMY) 	-DG_LOG_DOMAIN=\"Gdk\"		-I$(top_srcdir)			-DG_ENABLE_DEBUG 		-DUSE_XIM					-I/usr/lib/glib/include -D_REENTRANT			 -I/usr/xorg/include/ 		)


#
# libraries to compile and install
#
lib_LTLIBRARIES = libgdk.la

# libtool stuff: set version and export symbols for resolving
libgdkincludedir = $(includedir)/gtk-1.2/gdk
libgdk_la_LDFLAGS = $(strip $(STRIP_DUMMY) 	-version-info $(LT_CURRENT):$(LT_REVISION):$(LT_AGE) 	-release $(LT_RELEASE) 	-export-dynamic 	-L/usr/lib -rdynamic -lgmodule -lglib -ldl		  -L/usr/xorg/lib		-lXext -lX11 		-lm		)


#
# setup source file variables
#
# GDK header files for public installation (non-generated)
gdk_public_h_sources = $(strip $(STRIP_DUMMY) 	gdk.h			gdkcursors.h		gdkrgb.h		gdki18n.h		gdkkeysyms.h		gdkprivate.h		gdktypes.h		gdkx.h		)

gdk_c_sources = $(strip $(STRIP_DUMMY) 	gdk.c			gdkcc.c			gdkcolor.c		gdkcursor.c		gdkdnd.c		gdkdraw.c		gdkevents.c     	gdkfont.c		gdkgc.c			gdkglobals.c		gdkim.c			gdkimage.c		gdkinput.c		gdkinput.h		gdkinputnone.h  	gdkinputcommon.h 	gdkinputgxi.h		gdkinputxfree.h		gdkpixmap.c		gdkproperty.c		gdkrgb.c		gdkrectangle.c		gdkregion.c		gdkselection.c		gdkvisual.c		gdkwindow.c		gdkxid.c 		MwmUtil.h       	gxid_lib.h		gxid_proto.h	        gxid_lib.c	)


#
# setup GDK sources and their dependancies
#
libgdkinclude_HEADERS = $(gdk_public_h_sources)
libgdk_la_SOURCES = $(gdk_c_sources)
MAINTAINERCLEANFILES =  
EXTRA_HEADERS =  
EXTRA_DIST =   

#
# extra programs
#
EXTRA_PROGRAMS = gxid
bin_PROGRAMS = 
LDADDS = $(strip $(STRIP_DUMMY) 	  -L/usr/xorg/lib		-lXext -lX11 		-L/usr/lib -rdynamic -lgmodule -lglib -ldl		-lm		)

gxid_SOURCES = gxid.c
gxid_LDADD = $(LDADDS)
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
LTLIBRARIES =  $(lib_LTLIBRARIES)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I..
CPPFLAGS = 
LDFLAGS = -static-libgcc
LIBS =  
X_CFLAGS =  -I/usr/xorg/include/
X_LIBS =  -L/usr/xorg/lib
X_EXTRA_LIBS = 
X_PRE_LIBS =  -lSM -lICE
libgdk_la_LIBADD = 
libgdk_la_OBJECTS =  gdk.lo gdkcc.lo gdkcolor.lo gdkcursor.lo gdkdnd.lo \
gdkdraw.lo gdkevents.lo gdkfont.lo gdkgc.lo gdkglobals.lo gdkim.lo \
gdkimage.lo gdkinput.lo gdkpixmap.lo gdkproperty.lo gdkrgb.lo \
gdkrectangle.lo gdkregion.lo gdkselection.lo gdkvisual.lo gdkwindow.lo \
gdkxid.lo gxid_lib.lo
PROGRAMS =  $(bin_PROGRAMS)

gxid_OBJECTS =  gxid.o
gxid_DEPENDENCIES = 
gxid_LDFLAGS = 
CFLAGS = -O2 -Wall
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
HEADERS =  $(libgdkinclude_HEADERS)

DIST_COMMON =  COPYING Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(libgdk_la_SOURCES) $(gxid_SOURCES)
OBJECTS = $(libgdk_la_OBJECTS) $(gxid_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .lo .o .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps gdk/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-libLTLIBRARIES:

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)

distclean-libLTLIBRARIES:

maintainer-clean-libLTLIBRARIES:

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libdir)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo "$(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(libdir)/$$p"; \
	    $(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  $(LIBTOOL)  --mode=uninstall rm -f $(DESTDIR)$(libdir)/$$p; \
	done

.c.o:
	$(COMPILE) -c $<

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libgdk.la: $(libgdk_la_OBJECTS) $(libgdk_la_DEPENDENCIES)
	$(LINK) -rpath $(libdir) $(libgdk_la_LDFLAGS) $(libgdk_la_OBJECTS) $(libgdk_la_LIBADD) $(LIBS)

mostlyclean-binPROGRAMS:

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

distclean-binPROGRAMS:

maintainer-clean-binPROGRAMS:

install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`"; \
	    $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	list='$(bin_PROGRAMS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	done

gxid: $(gxid_OBJECTS) $(gxid_DEPENDENCIES)
	@rm -f gxid
	$(LINK) $(gxid_LDFLAGS) $(gxid_OBJECTS) $(gxid_LDADD) $(LIBS)

install-libgdkincludeHEADERS: $(libgdkinclude_HEADERS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libgdkincludedir)
	@list='$(libgdkinclude_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d= ; else d="$(srcdir)/"; fi; \
	  echo " $(INSTALL_DATA) $$d$$p $(DESTDIR)$(libgdkincludedir)/$$p"; \
	  $(INSTALL_DATA) $$d$$p $(DESTDIR)$(libgdkincludedir)/$$p; \
	done

uninstall-libgdkincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	list='$(libgdkinclude_HEADERS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(libgdkincludedir)/$$p; \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = gdk

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
gdk.lo gdk.o : gdk.c ../config.h gdk.h gdktypes.h gdkcursors.h gdkrgb.h \
	gdkprivate.h gdkinput.h gdkx.h gdkprivate.h gdki18n.h \
	gdkkeysyms.h
gdkcc.lo gdkcc.o : gdkcc.c gdk.h gdktypes.h gdkcursors.h gdkrgb.h \
	gdkprivate.h gdkx.h gdkprivate.h
gdkcolor.lo gdkcolor.o : gdkcolor.c gdk.h gdktypes.h gdkcursors.h \
	gdkrgb.h gdkprivate.h gdkx.h gdkprivate.h
gdkcursor.lo gdkcursor.o : gdkcursor.c gdk.h gdktypes.h gdkcursors.h \
	gdkrgb.h gdkprivate.h
gdkdnd.lo gdkdnd.o : gdkdnd.c gdkx.h gdkprivate.h gdktypes.h \
	gdkcursors.h gdk.h gdkrgb.h
gdkdraw.lo gdkdraw.o : gdkdraw.c gdk.h gdktypes.h gdkcursors.h gdkrgb.h \
	gdkprivate.h
gdkevents.lo gdkevents.o : gdkevents.c gdk.h gdktypes.h gdkcursors.h \
	gdkrgb.h gdkx.h gdkprivate.h gdkprivate.h gdkkeysyms.h \
	../config.h gdkinput.h
gdkfont.lo gdkfont.o : gdkfont.c gdk.h gdktypes.h gdkcursors.h gdkrgb.h \
	gdkprivate.h ../config.h
gdkgc.lo gdkgc.o : gdkgc.c gdk.h gdktypes.h gdkcursors.h gdkrgb.h \
	gdkprivate.h
gdkglobals.lo gdkglobals.o : gdkglobals.c gdktypes.h gdkcursors.h \
	gdkprivate.h gdktypes.h ../config.h
gdkim.lo gdkim.o : gdkim.c gdk.h gdktypes.h gdkcursors.h gdkrgb.h \
	gdkprivate.h gdki18n.h gdkx.h gdkprivate.h ../config.h
gdkimage.lo gdkimage.o : gdkimage.c ../config.h gdk.h gdktypes.h \
	gdkcursors.h gdkrgb.h gdkprivate.h
gdkinput.lo gdkinput.o : gdkinput.c ../config.h gdk.h gdktypes.h \
	gdkcursors.h gdkrgb.h gdkx.h gdkprivate.h gdkprivate.h \
	gdkinput.h gdkinputnone.h gdkinputcommon.h gdkinputxfree.h \
	gdkinputgxi.h
gdkpixmap.lo gdkpixmap.o : gdkpixmap.c ../config.h gdk.h gdktypes.h \
	gdkcursors.h gdkrgb.h gdkprivate.h
gdkproperty.lo gdkproperty.o : gdkproperty.c gdk.h gdktypes.h \
	gdkcursors.h gdkrgb.h gdkprivate.h
gdkrectangle.lo gdkrectangle.o : gdkrectangle.c gdk.h gdktypes.h \
	gdkcursors.h gdkrgb.h
gdkregion.lo gdkregion.o : gdkregion.c gdk.h gdktypes.h gdkcursors.h \
	gdkrgb.h gdkprivate.h
gdkrgb.lo gdkrgb.o : gdkrgb.c ../config.h gdk.h gdktypes.h gdkcursors.h \
	gdkrgb.h gdkprivate.h gdkrgb.h
gdkselection.lo gdkselection.o : gdkselection.c gdk.h gdktypes.h \
	gdkcursors.h gdkrgb.h gdkprivate.h gdkx.h gdkprivate.h
gdkvisual.lo gdkvisual.o : gdkvisual.c gdk.h gdktypes.h gdkcursors.h \
	gdkrgb.h gdkprivate.h gdkx.h gdkprivate.h
gdkwindow.lo gdkwindow.o : gdkwindow.c gdk.h gdktypes.h gdkcursors.h \
	gdkrgb.h ../config.h gdkinput.h gdkprivate.h MwmUtil.h
gdkxid.lo gdkxid.o : gdkxid.c gdkprivate.h gdktypes.h gdkcursors.h
gxid_lib.lo gxid_lib.o : gxid_lib.c ../config.h gxid_lib.h gxid_proto.h

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-libLTLIBRARIES install-binPROGRAMS
install-exec: install-exec-am

install-data-am: install-libgdkincludeHEADERS
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-libLTLIBRARIES uninstall-binPROGRAMS \
		uninstall-libgdkincludeHEADERS
uninstall: uninstall-am
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(HEADERS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(libdir) $(DESTDIR)$(bindir) \
		$(DESTDIR)$(libgdkincludedir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
mostlyclean-am:  mostlyclean-libLTLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-binPROGRAMS \
		mostlyclean-tags mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-libLTLIBRARIES clean-compile clean-libtool \
		clean-binPROGRAMS clean-tags clean-generic \
		mostlyclean-am

clean: clean-am

distclean-am:  distclean-libLTLIBRARIES distclean-compile \
		distclean-libtool distclean-binPROGRAMS distclean-tags \
		distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-libLTLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-binPROGRAMS maintainer-clean-tags \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-libLTLIBRARIES distclean-libLTLIBRARIES \
clean-libLTLIBRARIES maintainer-clean-libLTLIBRARIES \
uninstall-libLTLIBRARIES install-libLTLIBRARIES mostlyclean-compile \
distclean-compile clean-compile maintainer-clean-compile \
mostlyclean-libtool distclean-libtool clean-libtool \
maintainer-clean-libtool mostlyclean-binPROGRAMS distclean-binPROGRAMS \
clean-binPROGRAMS maintainer-clean-binPROGRAMS uninstall-binPROGRAMS \
install-binPROGRAMS uninstall-libgdkincludeHEADERS \
install-libgdkincludeHEADERS tags mostlyclean-tags distclean-tags \
clean-tags maintainer-clean-tags distdir info-am info dvi-am dvi check \
check-am installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


#
# rules to generate built sources
#
# we only need to remake these headers once a new X version is released
X-derived-headers:
	sed -e 's/^#define[ 	]*XC\([^ 	]*\)[ 	]*\([^ 	]*\)[ 	]*.*$$/GDK\1 = \2,/' \
	    -e 'tb' -e 'd' -e ':b' \
	    -e 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/' \
	    < /usr/xorg/include//X11/cursorfont.h > gdkcursors.h ; \
	sed -e 's/^#define[ 	]*XK\([^ 	]*\)[ 	]*\([^ 	]*\)[ 	]*.*$$/#define GDK\1 \2/' \
	    -e 'tb' -e 'd' -e ':b' -e 's/ 0X/ 0x/' \
	    < /usr/xorg/include//X11/keysymdef.h > gdkkeysyms.h

.PHONY: files

files:
	@files=`ls $(DISTFILES) 2> /dev/null `; for p in $$files; do \
	  echo $$p; \
	done

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
