#!/bin/sh

rm -r /freerdp/*
rm -r ./CMakeCache.txt
make clean

cmake \
-DBUILD_SHARED_LIBS=OFF \
-DMONOLITHIC_BUILD=ON \
-DSTATIC_CHANNELS=ON \
-DVENDOR=TSOL \
-DWITH_MANPAGES=OFF \
-DCMAKE_INSTALL_PREFIX:PATH=/ \
-DWITH_ALSA=ON \
-DWITH_PCSC=ON \
-DWITH_SSE2=ON \
-DWITH_JPEG=OFF \
-DWITH_CUPS=OFF \
-DWITH_PULSE=OFF \
-DWITH_FFMPEG=OFF \
-DWITH_GSTREAMER=OFF \
-DWITH_OPENSLES=OFF \
-DWITH_GPROF=OFF \
-DWITH_DIRECTFB=OFF \
-DWITH_IPP=OFF \
-DWITH_NPP=OFF \
-DWITH_SERVER=OFF .
#-DCMAKE_BUILD_TYPE:STRING=Debug \
#-DWITH_DEBUG_SCARD=ON .
#-DWITH_DEBUG_GDI=ON \
#-DWITH_DEBUG_ORDERS=ON \
#-DWITH_DEBUG_WND=ON \
#-DWITH_DEBUG_X11=ON \
#-DWITH_DEBUG_X11_CLIPRDR=ON \
#-DWITH_DEBUG_X11_LOCAL_MOVESIZE=ON \
 
#-DCMAKE_BUILD_TYPE=Test \



make ; make install