#
# Makefile for linux/drivers/platform/x86
# x86 Platform-Specific Drivers
#
#obj-$(CPTCFG_ASUS_LAPTOP)	+= asus-laptop.o
#obj-$(CPTCFG_ASUS_WMI)		+= asus-wmi.o
#obj-$(CPTCFG_ASUS_NB_WMI)	+= asus-nb-wmi.o
#obj-$(CPTCFG_EEEPC_LAPTOP)	+= eeepc-laptop.o
#obj-$(CPTCFG_EEEPC_WMI)		+= eeepc-wmi.o
#obj-$(CPTCFG_MSI_LAPTOP)	+= msi-laptop.o
#obj-$(CPTCFG_ACPI_CMPC)		+= classmate-laptop.o
#obj-$(CPTCFG_COMPAL_LAPTOP)	+= compal-laptop.o
#obj-$(CPTCFG_DELL_LAPTOP)	+= dell-laptop.o
#obj-$(CPTCFG_DELL_WMI)		+= dell-wmi.o
#obj-$(CPTCFG_DELL_WMI_AIO)	+= dell-wmi-aio.o
#obj-$(CPTCFG_ACER_WMI)		+= acer-wmi.o
#obj-$(CPTCFG_ACERHDF)		+= acerhdf.o
#obj-$(CPTCFG_HP_ACCEL)		+= hp_accel.o
#obj-$(CPTCFG_HP_WMI)		+= hp-wmi.o
#obj-$(CPTCFG_AMILO_RFKILL)	+= amilo-rfkill.o
#obj-$(CPTCFG_TC1100_WMI)	+= tc1100-wmi.o
#obj-$(CPTCFG_SONY_LAPTOP)	+= sony-laptop.o
#obj-$(CPTCFG_IDEAPAD_LAPTOP)	+= ideapad-laptop.o
#obj-$(CPTCFG_THINKPAD_ACPI)	+= thinkpad_acpi.o
#obj-$(CPTCFG_SENSORS_HDAPS)	+= hdaps.o
#obj-$(CPTCFG_FUJITSU_LAPTOP)	+= fujitsu-laptop.o
#obj-$(CPTCFG_FUJITSU_TABLET)	+= fujitsu-tablet.o
#obj-$(CPTCFG_PANASONIC_LAPTOP)	+= panasonic-laptop.o
#obj-$(CPTCFG_INTEL_MENLOW)	+= intel_menlow.o
#obj-$(CPTCFG_ACPI_WMI)		+= wmi.o
#obj-$(CPTCFG_MSI_WMI)		+= msi-wmi.o
#obj-$(CPTCFG_TOPSTAR_LAPTOP)	+= topstar-laptop.o

# toshiba_acpi must link after wmi to ensure that wmi devices are found
# before toshiba_acpi initializes
#obj-$(CPTCFG_ACPI_TOSHIBA)	+= toshiba_acpi.o
#
#obj-$(CPTCFG_TOSHIBA_BT_RFKILL)	+= toshiba_bluetooth.o
#obj-$(CPTCFG_INTEL_SCU_IPC)	+= intel_scu_ipc.o
#obj-$(CPTCFG_INTEL_SCU_IPC_UTIL) += intel_scu_ipcutil.o
#obj-$(CPTCFG_INTEL_MFLD_THERMAL) += intel_mid_thermal.o
obj-$(CPTCFG_INTEL_IPS)		+= intel_ips.o
#obj-$(CPTCFG_GPIO_INTEL_PMIC)	+= intel_pmic_gpio.o
#obj-$(CPTCFG_XO1_RFKILL)	+= xo1-rfkill.o
#obj-$(CPTCFG_XO15_EBOOK)	+= xo15-ebook.o
#obj-$(CPTCFG_IBM_RTL)		+= ibm_rtl.o
#obj-$(CPTCFG_SAMSUNG_LAPTOP)	+= samsung-laptop.o
#obj-$(CPTCFG_MXM_WMI)		+= mxm-wmi.o
#obj-$(CPTCFG_INTEL_MID_POWER_BUTTON)	+= intel_mid_powerbtn.o
#obj-$(CPTCFG_INTEL_OAKTRAIL)	+= intel_oaktrail.o
#obj-$(CPTCFG_SAMSUNG_Q10)	+= samsung-q10.o
#obj-$(CPTCFG_APPLE_GMUX)	+= apple-gmux.o
#obj-$(CPTCFG_CHROMEOS_LAPTOP)	+= chromeos_laptop.o
#obj-$(CPTCFG_INTEL_RST)		+= intel-rst.o
#obj-$(CPTCFG_INTEL_SMARTCONNECT)	+= intel-smartconnect.o
#
#obj-$(CPTCFG_PVPANIC)           += pvpanic.o
