# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

# The name of the module.


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /usr
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/gdk-pixbuf
pkglibdir = $(libdir)/gdk-pixbuf
pkgincludedir = $(includedir)/gdk-pixbuf

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
AS = @AS@
CC = i486-TSOL-linux-gnu-gcc
CPP = i486-TSOL-linux-gnu-gcc -E
DLLTOOL = @DLLTOOL@
GDK_PIXBUF_DIR = /source/gtk/1.2.0/gdk-pixbuf-0.10.0
GDK_PIXBUF_INCLUDEDIR = -I${prefix}/include -I/usr/xorg/include/ -I/usr/lib/glib/include
GDK_PIXBUF_LIBDIR = -L${libdir}
GDK_PIXBUF_LIBS = -L/usr/lib -rdynamic -lgmodule -lglib -ldl -lgdk_pixbuf -L/usr/lib -L/usr/xorg/lib -lgtk -lgdk -rdynamic -lgmodule -lglib -ldl -lXext -lX11 -lm
GDK_PIXBUF_MAJOR = 0
GDK_PIXBUF_MICRO = 0
GDK_PIXBUF_MINOR = 10
GDK_PIXBUF_VERSION = 0.10.0
GDK_PIXBUF_XLIB_INCLUDEDIR = -I${prefix}/include -I/usr/xorg/include/ -I/usr/lib/glib/include
GDK_PIXBUF_XLIB_LIBDIR = -L${libdir}
GDK_PIXBUF_XLIB_LIBS = -L/usr/lib -rdynamic -lgmodule -lglib -ldl -lgdk_pixbuf_xlib 
GLIB_CFLAGS = -I/usr/lib/glib/include
GLIB_CONFIG = /usr/bin/glib-config
GLIB_LIBS = -L/usr/lib -rdynamic -lgmodule -lglib -ldl
GMODULE_FLAGS = -I/usr/lib/glib/include
GMODULE_LIBS = -L/usr/lib -rdynamic -lgmodule -lglib -ldl
GNOMECANVASPIXBUF_INCLUDEDIR = -I${prefix}/include -I/usr/xorg/include/ -I/usr/lib/glib/include
GNOMECANVASPIXBUF_LIBDIR = -L${libdir}
GNOMECANVASPIXBUF_LIBS = -L/usr/lib -rdynamic -lgmodule -lglib -ldl -lgdk_pixbuf -L/usr/lib -L/usr/xorg/lib -lgtk -lgdk -rdynamic -lgmodule -lglib -ldl -lXext -lX11 -lm -lgnomecanvaspixbuf
GNOME_CFLAGS = 
GNOME_CONFIG = no
GNOME_LIBS = 
GTKDOC = false
GTK_CFLAGS = -I/usr/xorg/include/ -I/usr/lib/glib/include
GTK_CONFIG = /usr/bin/gtk-config
GTK_LIBS = -L/usr/lib -L/usr/xorg/lib -lgtk -lgdk -rdynamic -lgmodule -lglib -ldl -lXext -lX11 -lm
HAVE_GTK_DOC = 
LIBJPEG = -ljpeg
LIBPNG = -lpng -lz
LIBTIFF = -ltiff
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
MAINT = #
MAKEINFO = /source/gtk/1.2.0/gdk-pixbuf-0.10.0/missing makeinfo
OBJDUMP = @OBJDUMP@
PACKAGE = gdk-pixbuf
RANLIB = ranlib
STATIC_LIB_DEPS = -ltiff -ljpeg -lpng -lz
VERSION = 0.10.0

DOC_MODULE = gdk-pixbuf

# The top-level SGML file.
DOC_MAIN_SGML_FILE = gdk-pixbuf.sgml

# The directory containing the source code (if it contains documentation).
DOC_SOURCE_DIR = $(GDK_PIXBUF_DIR)/gdk-pixbuf

CFLAGS = `gnome-config --cflags gnomeui gdk_pixbuf gnomecanvaspixbuf`
LDFLAGS = `gnome-config --libs gnomeui gdk_pixbuf gnomecanvaspixbuf`

HTML_DIR = $(datadir)/gnome/html

TARGET_DIR = $(HTML_DIR)/$(DOC_MODULE)

tmpl_sources =  	tmpl/animation.sgml					tmpl/creating.sgml					tmpl/file-loading.sgml					tmpl/from-drawables.sgml				tmpl/gdk-pixbuf-loader.sgml				tmpl/gdk-pixbuf-unused.sgml				tmpl/gdk-pixbuf.sgml					tmpl/gnome-canvas-pixbuf.sgml				tmpl/refcounting.sgml					tmpl/rendering.sgml					tmpl/scaling.sgml					tmpl/util.sgml						tmpl/gdk-pixbuf-xlib-from-drawables.sgml		tmpl/gdk-pixbuf-xlib-init.sgml				tmpl/gdk-pixbuf-xlib-rendering.sgml			tmpl/gdk-pixbuf-xlib-rgb.sgml


gdk_pixbuf_docdir = $(HTML_DIR)
gdk_pixbuf_doc_DATA =  	gdk-pixbuf.html				gdk-pixbuf.hierarchy			gdk-pixbuf.types			gdk-pixbuf-decl.txt			gdk-pixbuf-sections.txt


content_files =  	compiling.sgml				gdk-pixbuf.sgml				porting-from-imlib.sgml


EXTRA_DIST =  	$(gdk_pixbuf_doc_DATA)			$(content_files)

mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
DATA =  $(gdk_pixbuf_doc_DATA)

DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
all: all-redirect
.SUFFIXES:
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps doc/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


install-gdk_pixbuf_docDATA: $(gdk_pixbuf_doc_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(gdk_pixbuf_docdir)
	@list='$(gdk_pixbuf_doc_DATA)'; for p in $$list; do \
	  if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(gdk_pixbuf_docdir)/$$p"; \
	    $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(gdk_pixbuf_docdir)/$$p; \
	  else if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(gdk_pixbuf_docdir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(gdk_pixbuf_docdir)/$$p; \
	  fi; fi; \
	done

uninstall-gdk_pixbuf_docDATA:
	@$(NORMAL_UNINSTALL)
	list='$(gdk_pixbuf_doc_DATA)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(gdk_pixbuf_docdir)/$$p; \
	done
tags: TAGS
TAGS:


distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = doc

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) top_distdir="$(top_distdir)" distdir="$(distdir)" dist-hook
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am: install-gdk_pixbuf_docDATA install-data-local
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-gdk_pixbuf_docDATA
uninstall: uninstall-am
all-am: Makefile $(DATA)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(gdk_pixbuf_docdir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-generic mostlyclean-am clean-local

clean: clean-am

distclean-am:  distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-generic distclean-am \
		maintainer-clean-local
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: uninstall-gdk_pixbuf_docDATA install-gdk_pixbuf_docDATA tags \
distdir info-am info dvi-am dvi check check-am installcheck-am \
installcheck install-exec-am install-exec install-data-local \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


#gdk-pixbuf.html: html/book1.html
#	-cd $(srcdir) && cp html/book1.html gdk-pixbuf.html
gdk-pixbuf.html:

html/book1.html: sgml/gdk-pixbuf-doc.bottom $(content_files)
	$(MAKE) html

sgml/gdk-pixbuf-doc.bottom: $(tmpl_sources)
	$(MAKE) sgml

scan:
	-(cd $(srcdir) \
	&& env CFLAGS=$(CFLAGS) LDFLAGS=$(LDFLAGS) \
		 gtkdoc-scanobj --module=$(DOC_MODULE) \
	&& gtkdoc-scan --module=$(DOC_MODULE) --source-dir=$(DOC_SOURCE_DIR) --ignore-headers="pixops.h pixops-internal.h" )

templates: scan
	cd $(srcdir) && gtkdoc-mktmpl --module=$(DOC_MODULE)

sgml:
	cd $(srcdir) \
	&& gtkdoc-mkdb --module=$(DOC_MODULE) --source-dir=$(DOC_SOURCE_DIR)

html:
	test -d $(srcdir)/html || mkdir $(srcdir)/html
	-cd $(srcdir)/html && gtkdoc-mkhtml $(DOC_MODULE) ../$(DOC_MAIN_SGML_FILE)

clean-local:
	rm -f *~ *.bak *.signals *-unused.txt

maintainer-clean-local: clean
	cd $(srcdir) && rm -rf sgml html $(DOC_MODULE)-decl-list.txt $(DOC_MODULE)-decl.txt

install-data-local:
	$(mkinstalldirs) $(DESTDIR)$(TARGET_DIR)
	(installfiles=`echo $(srcdir)/html/*.html`; \
	if test "$$installfiles" = '$(srcdir)/html/*.html'; \
	then echo '-- Nothing to install' ; \
	else \
	  for i in $$installfiles; do \
	    echo '-- Installing '$$i ; \
	    $(INSTALL_DATA) $$i $(DESTDIR)$(TARGET_DIR); \
	  done; \
	  echo '-- Installing $(srcdir)/html/index.sgml' ; \
	  $(INSTALL_DATA) $(srcdir)/html/index.sgml $(DESTDIR)$(TARGET_DIR); \
	  echo '-- Fixing Crossreferences' ; \
	  gtkdoc-fixxref --module=$(DOC_MODULE) --html-dir=$(HTML_DIR)|| true; \
	fi)

dist-hook:
	mkdir $(distdir)/html
	mkdir $(distdir)/sgml
	mkdir $(distdir)/tmpl
	-cp $(srcdir)/html/*.html $(srcdir)/html/*.css $(distdir)/html
	-cp $(srcdir)/tmpl/*.sgml $(distdir)/tmpl
	-cp $(srcdir)/sgml/*.sgml $(distdir)/sgml
	-cp $(srcdir)/sgml/*.bottom $(srcdir)/sgml/*.top $(distdir)/sgml

.PHONY : html sgml templates scan

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
