.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH VOID 4 "xf86-input-void 1.4.0" "X Version 11"
.SH NAME
void \- null input driver
.SH SYNOPSIS
.nf
.B "Section \*qInputDevice\*q"
.BI "  Identifier \*q" idevname \*q
.B  "  Driver \*qvoid\*q"
\ \ ...
.B EndSection
.fi
.SH DESCRIPTION
.B void 
is an dummy/null Xorg input driver.  It doesn't connect to any
physical device, and it never delivers any events.  It functions as
both a pointer and keyboard device, and may be used as X server's core
pointer and/or core keyboard.  It's purpose is to allow X servers pre
version 1.4 to operate without a core pointer and/or core keyboard.
.SH CONFIGURATION DETAILS
Please refer to xorg.conf(5) for general configuration
details and for options that can be used with all input drivers.  This
driver doesn't have any configuration options in addition to those.
.SH "SEE ALSO"
Xorg(1), xorg.conf(5), Xserver(1), X(7).
