include /source/fbpanel/fbpanel-5.6/config.mk

SUBDIRS = dclock deskno deskno2 icons image launchbar menu 
SUBDIRS += pager separator space systray taskbar tclock test wincmd
SUBDIRS += chart net cpu mem genmon


include /source/fbpanel/fbpanel-5.6/rules.mk
