/* config.h.  Generated by configure.  */
/* autoconf/config.h.in.  Generated from autoconf/configure.in by autoheader.  */

/* Define if you want support for Greek Elot-928 & IBM-437 keyboard */
/* #undef GREEK_SUPPORT */

/* Define if you want the depth of scrollbars and menus to be less */
/* #undef HALFSHADOW */

/* Define to 1 if you have the <assert.h> header file. */
#define HAVE_ASSERT_H 1

/* Define to 1 if you have the `atexit' function. */
#define HAVE_ATEXIT 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define if you have _GNU_SOURCE getpt() */
#define HAVE_GETPT 1

/* Define to 1 if you have the `grantpt' function. */
#define HAVE_GRANTPT 1

/* Define to 1 if you have the <grp.h> header file. */
#define HAVE_GRP_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `isastream' function. */
#define HAVE_ISASTREAM 1

/* Define to 1 if you have the <lastlog.h> header file. */
#define HAVE_LASTLOG_H 1

/* Define to 1 if you have the <libc.h> header file. */
/* #undef HAVE_LIBC_H */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `nanosleep' function. */
#define HAVE_NANOSLEEP 1

/* Define if nl_langinfo(CODESET) works */
#define HAVE_NL_LANGINFO 1

/* Define to 1 if you have the `on_exit' function. */
#define HAVE_ON_EXIT 1

/* Define to 1 if you have the `openpty' function. */
/* #undef HAVE_OPENPTY */

/* Define to 1 if you have the `revoke' function. */
/* #undef HAVE_REVOKE */

/* Define to 1 if you have the `seteuid' function. */
#define HAVE_SETEUID 1

/* Define if plain old setlocale works */
#define HAVE_SETLOCALE 1

/* Define to 1 if you have the `setpgid' function. */
#define HAVE_SETPGID 1

/* Define to 1 if you have the `setpgrp' function. */
#define HAVE_SETPGRP 1

/* Define to 1 if you have the `setreuid' function. */
#define HAVE_SETREUID 1

/* Define to 1 if you have the `setsid' function. */
#define HAVE_SETSID 1

/* Define to 1 if you have the `setutent' function. */
#define HAVE_SETUTENT 1

/* Define to 1 if you have the <stdarg.h> header file. */
#define HAVE_STDARG_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define if utmp.h or lastlog.h has struct lastlog */
#define HAVE_STRUCT_LASTLOG 1

/* Define if utmpx.h or lastlog.h has struct lastlogx */
/* #undef HAVE_STRUCT_LASTLOGX */

/* Define if utmp.h has struct utmp */
#define HAVE_STRUCT_UTMP 1

/* Define if utmpx.h has struct utmpx */
#define HAVE_STRUCT_UTMPX 1

/* Define to 1 if you have the <sys/byteorder.h> header file. */
/* #undef HAVE_SYS_BYTEORDER_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/sockio.h> header file. */
/* #undef HAVE_SYS_SOCKIO_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/strredir.h> header file. */
/* #undef HAVE_SYS_STRREDIR_H */

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <termios.h> header file. */
#define HAVE_TERMIOS_H 1

/* Define to 1 if you have the `ttyslot' function. */
#define HAVE_TTYSLOT 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `unlockpt' function. */
#define HAVE_UNLOCKPT 1

/* Define to 1 if you have the `unsetenv' function. */
#define HAVE_UNSETENV 1

/* Define to 1 if you have the `updwtmp' function. */
#define HAVE_UPDWTMP 1

/* Define to 1 if you have the <utmpx.h> header file. */
#define HAVE_UTMPX_H 1

/* Define if struct utmpx contains ut_host */
#define HAVE_UTMPX_HOST 1

/* Define to 1 if you have the <utmp.h> header file. */
#define HAVE_UTMP_H 1

/* Define if struct utmp contains ut_host */
#define HAVE_UTMP_HOST 1

/* Define if struct utmp contains ut_pid */
#define HAVE_UTMP_PID 1

/* Define if Xlocale support works */
#define HAVE_XLOCALE 1

/* Define if you have XPointer typedef */
#define HAVE_XPOINTER 1

/* Define if setlocale (defined to Xsetlocale) works */
/* #undef HAVE_XSETLOCALE */

/* Define to 1 if you have the `_getpty' function. */
/* #undef HAVE__GETPTY */

/* Define if lastlog is provided via a directory */
/* #undef LASTLOG_IS_DIR */

/* Define if you want to have lastlog support when utmp/utmpx is enabled */
/* #undef LASTLOG_SUPPORT */

/* Build shared library version - specify via configure only */
/* #undef LIBRXVT */

/* Define if you want Menubar support */
/* #undef MENUBAR */

/* Define to have CTRL cause wheel events to accelerate scrolling. Release
   CTRL to halt scrolling */
/* #undef MOUSE_SLIP_WHEELING */

/* Define to use wheel events (button4 and button5) to scroll */
/* #undef MOUSE_WHEEL */

/* Define default multichar glyph encoding */
/* #undef MULTICHAR_ENCODING */

/* Define to enable multichar glyph language support */
/* #undef MULTICHAR_SET */

/* Support NeXT style scrollbars - specify via configure only */
/* #undef NEXT_SCROLLBAR */

/* Define if you don't want support for the backspace key */
#define NO_BACKSPACE_KEY 1

/* Define if you don't want support for the (non-keypad) delete key */
#define NO_DELETE_KEY 1

/* Define if you don't want handling for rarely used features */
#define NO_FRILLS 1

/* Define if you don't want support linespace */
#define NO_LINESPACE 1

/* Define to remove xterm style mouse selection */
/* #undef NO_NEW_SELECTION */

/* Define to remove old rxvt (ver 2.20 and before) style selection */
#define NO_OLD_SELECTION 1

/* Define if you don't want any resources read */
#define NO_RESOURCES 1

/* Define for continual scrolling when you keep the scrollbar button pressed
   */
#define NO_SCROLLBAR_BUTTON_CONTINUAL_SCROLLING 1

/* Disable the secondary screen. Many programs use the secondary screen as
   their workplace */
#define NO_SECONDARY_SCREEN 1

/* Define if you don't need to use our replacement string functions */
#define NO_STRINGS 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to use a 24 bit visual if the screen has 24 bit mode */
/* #undef PREFER_24BIT */

/* Define if you need function prototypes */
#define PROTOTYPES 1

/* Define for first char in devptyXX */
#define PTYCHAR1 "p"

/* Define for second char in devptyXX */
#define PTYCHAR2 "0123456789"

/* Define for this pty type */
/* #undef PTYS_ARE_CLONE */

/* Define for this pty type */
#define PTYS_ARE_GETPT 1

/* Define for this pty type */
/* #undef PTYS_ARE_GETPTY */

/* Define for this pty type */
/* #undef PTYS_ARE_NUMERIC */

/* Define for this pty type */
/* #undef PTYS_ARE_OPENPTY */

/* Define for this pty type */
/* #undef PTYS_ARE_PTC */

/* Define for this pty type */
/* #undef PTYS_ARE_PTMX */

/* Define for this pty type */
#define PTYS_ARE_SEARCHED 1

/* Define for this pty type */
/* #undef PTYS_ARE__GETPTY */

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define if you want Rob Nation's own graphic mode */
/* #undef RXVT_GRAPHICS */

/* Define location of lastlogx */
/* #undef RXVT_LASTLOGX_FILE */

/* Define location of lastlog */
#define RXVT_LASTLOG_FILE "/var/log/lastlog"

/* Support Rxvt original style scrollbars - specify via configure only */
/* #undef RXVT_SCROLLBAR */

/* Set TERMINFO value to the value given by configure */
/* #undef RXVT_TERMINFO */

/* Define location of utmpx */
/* #undef RXVT_UTMPX_FILE */

/* Define location of utmp */
#define RXVT_UTMP_FILE "/var/run/utmp"

/* Define location of wtmpx */
/* #undef RXVT_WTMPX_FILE */

/* Define location of wtmp */
#define RXVT_WTMP_FILE "/var/log/wtmp"

/* The size of a `char', as computed by sizeof. */
#define SIZEOF_CHAR 1

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `int *', as computed by sizeof. */
#define SIZEOF_INT_P 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of a `long long', as computed by sizeof. */
#define SIZEOF_LONG_LONG 8

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* Define to use "smart" resize behavior */
/* #undef SMART_RESIZE */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Set TERM to the value given by configure */
/* #undef TERMENV */

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define if you want your background to use the parent window background */
/* #undef TRANSPARENT */

/* Define location of ttys/ttytab */
/* #undef TTYTAB_FILENAME */

/* Define if you want 256 colour support */
/* #undef TTY_256COLOR */

/* Define to change gid of ttys to group tty */
/* #undef TTY_GID_SUPPORT */

/* Define if you want to use XGetDefault instead of our internal version */
/* #undef USE_XGETDEFAULT */

/* Define if you want to have XIM (X Input Method) protocol support - required
   for multibyte characters input */
/* #undef USE_XIM */

/* Define if you want to have utmp/utmpx support */
/* #undef UTMP_SUPPORT */

/* Define if you want to have wtmp support when utmp/utmpx is enabled */
/* #undef WTMP_SUPPORT */

/* Define if you want to have sexy-looking background pixmaps. Needs libXpm */
/* #undef XPM_BACKGROUND */

/* Define if you include <X11/xpm.h> on a normal include path (be careful) */
/* #undef XPM_INC_X11 */

/* Support Xterm style scrollbars - specify via configure only */
/* #undef XTERM_SCROLLBAR */

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Define to 1 if on AIX 3.
   System headers sometimes define this.
   We just want to avoid a redefinition error message.  */
#ifndef _ALL_SOURCE
/* # undef _ALL_SOURCE */
#endif

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef gid_t */

/* Define as `__inline' if that's what the C compiler calls it, or to nothing
   if it is not supported. */
/* #undef inline */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef mode_t */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef uid_t */
