include /build/source/fbpanel/fbpanel-6.1/config.mk

SRCS = meter.c 
LIBTARGET = meter.so


install:
	$(install) 755 $(LIBDIR)/fbpanel 755 $(LIBTARGET)

include /build/source/fbpanel/fbpanel-6.1/rules.mk
