.TH acpi_listen 8 "Nov 2003"
.\" Portions Copyright (c) 2003 Sun Microsystems
.\" Copyright (c) 2004 Tim Hockin (thockin@hockin.org)
.\" Some parts (C) 2003 - Gismo / Luca Capello <luca.pca.it> http://luca.pca.it
.SH NAME
acpi_listen \- ACPI event listener
.SH SYNOPSIS
\fBacpi_listen\fP [\fIoptions\fP]

.SH DESCRIPTION
\fBacpid\fP is the system-wide ACPI event catcher.  \fBacpi_listen\fP is a
simple shell-friendly tool which connects to acpid and listens for events.
When an event occurs, acpi_listen will print it on stdout.

.SH OPTIONS
.TP
.BI \-c "\fR, \fP" \--count " events"
Receive up to a maximum number of ACPI events, then exit.
.TP
.BI \-s "\fR, \fP" \--socketfile " filename"
This option changes the name of the UNIX domain socket which \fBacpid\fP opens.
Default is \fI/var/run/acpid.socket\fP.
.TP
.BI \-t "\fR, \fP" \--time " seconds"
Listen for the specified time in seconds, before exiting.
.TP
.BI \-v "\fR, \fP" \--version
Print version information and exit.
.TP
.BI \-h "\fR, \fP" \--help
Show help and exit.

.SH FILES
.PD 0
.B /var/run/acpid.socket
.PD

.SH BUGS
There are no known bugs.  To file bug reports, see \fBAUTHORS\fP below.
.SH SEE ALSO
acpid(8)
.SH AUTHORS
Ted Felix (www.tedfelix.com)
.br
Tim Hockin <thockin@hockin.org>
.br
Luca Capello <luca@pca.it>
.br

