#
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

ccflags-y = -Iinclude/drm
sis-y := sis_drv.o sis_mm.o

obj-$(CPTCFG_DRM_SIS)   += sis.o


