#!/bin/sh
. $TS_GLOBAL

pretty_padd()
{
	echo "[$1" | awk '{ printf "%18s", $0 }' | sed -e 's/\s/./g' | sed -e 's/\[/ /'
}

P_NAME=`pretty_padd $CLIENT_NAME`
P_IP=`pretty_padd $CLIENT_IP`
P_MAC=`pretty_padd $CLIENT_MAC`

if [ "`make_caps "$PONIX_LANG"`" = "RU" ] ; then
xdmenu_msgbox "
Ponix $TS_VERSION

2005-2014, ООО \\\"Терминальные Решeния\\\"

Пожалуйста посетите сайт http://t-sol.ru/
для обновлений, сообщений об ошибках и отзывов.

NAME $P_NAME
IP ..$P_IP
MAC .$P_MAC
" 20
else
xdmenu_msgbox "
Ponix $TS_VERSION

2005-2014, Terminal Solutions Ltd.

Please visit our website http://t-sol.ru/
for upgrades, bugreports and feedback!

NAME $P_NAME
IP ..$P_IP
MAC .$P_MAC
" 20
fi
