#!/bin/sh

. $TS_GLOBAL

# EDIT_SESID should be set before this xdmenu is executed
# this script is called only from edit_session.xd menu.
# it's purpose is to build a xdmenu menu file which is session specific
# and contains variables for the current type of session EDIT_SESID

SESTYPE=`sesvar ${EDIT_SESID} TYPE`
SESTYPE_CAPS=`make_caps $SESTYPE`
SESTYPE=`make_lower $SESTYPE`

if [ ! -e "/etc/cmd/$SESTYPE.xdmenu" ] ; then
	echo "# NO XMENU FOR SESSION TYPE='$SESTYPE'"
	exit 1
fi

load_lang $SESTYPE

BSEM_ITEM=10
(cat "/etc/cmd/$SESTYPE.xdmenu" | grep "^#" -v ) |
while read var typ def opt opt1
do
	if [ -z "$var" ] ; then continue ; fi
#	echo "VAR='$var' TYP='$typ' DEF='$def', opt='$opt'"
	if [ "$var" = "BREAK" ] ; then
		echo "XD_ITEM${BSEM_ITEM}=EMPTY"	
	else
	
		VALUE=`sestypevar_def ${EDIT_SESID} $var "$def"`
		if [ "$VALUE" = "NULL" ] ; then VALUE= ; fi

		MENUTITLE=`eval echo '$'LNG_SE_${SESTYPE_CAPS}_${var}`
		TEXT=`eval echo '$'LNG_SE_${SESTYPE_CAPS}_${var}_TEXT`

		if [ -z "$MENUTITLE" ] ; then MENUTITLE=$var ; fi
		if [ -z "$TEXT" ] ; then TEXT=$MENUTITLE ; fi

		MENUTITLE=$MENUTITLE" : "$VALUE
		
		echo "XD_ITEM${BSEM_ITEM}=\"$MENUTITLE\""

		if [ "$typ" = "SELECT" ] ; then
			echo "XD_RUN${BSEM_ITEM}=\"${XDMENU_SCRIPTS}/var_edit_select SESSION_${EDIT_SESID}_${SESTYPE_CAPS}_$var '$TEXT' $opt $opt1\""	
		elif [ "$typ" = "INPUT" ] ; then
			echo "XD_RUN${BSEM_ITEM}=\"${XDMENU_SCRIPTS}/var_edit_input SESSION_${EDIT_SESID}_${SESTYPE_CAPS}_$var '$TEXT' '$def'\""		
		else
			echo "# INVALID INPUT TYPE '$typ' for '$var'!"
			continue
		fi
	fi
		
	let BSEM_ITEM=BSEM_ITEM+1
done

