#!/bin/sh

# Now this script is invoked in cycle all the time from start-session
# if no sessions are active, and CM is not open - open a CM for user

. $TS_GLOBAL


let i=0
while [ $i -le $MAX_SESSIONS ] ; 
do
	SESSION_TYPE=`eval echo '$SESSION_'$i'_TYPE'`
	if [ -n "$SESSION_TYPE" ] ; then
		if is_session_running $i ; then
#			echo "There are other sessions ($i). No need to run anything!"
			exit 0
		fi
	fi
	let i=i+1
done

# This function loads client-speific functions file, executes are_sessions_running
# from it. Clients which use function file, but do not implement this function 
# (relying on session mechanism instead) must return 1 (not running).


if [  -e /etc/cmd/*.functions ] ; then
	
	RES=$(ls /etc/cmd/*.functions |
	while read ffile
	do
		. $ffile > /dev/null 2> /dev/null
		if are_sessions_running ; then
			echo "RUNNING"
			exit 0
		fi

	done
	)
	
	if [ "$RES" = "RUNNING" ] ; then
		exit 0
	fi
fi

# there are no running session
# so we need to run connection manager or sessions again

# connection_manager is open, do not AUTORUN or open another CM

if [ -n "`pidof connection_manager`" ] ; then
	exit 0
fi

if [ `make_caps "$RECONNECT_PROMPT"` = "OFF" ] ; then
	/etc/init.d/autostart start
	exit 0
fi

$CONNECTION_MANAGER &
exit 0
