#!/bin/sh

. $TS_GLOBAL
load_lang base

XD_HEIGHT=16
XD_ITEM=7

PKG_CFG_SCRIPTS_PATH=/etc/xdmenu/pkg_config_menu/

SRC_MENU=/etc/xdmenu/config_menu.xd
MENU_FILE=/tmp/config_menu.xd

cat $SRC_MENU > $MENU_FILE

FIRST=yes

ls -1 $PKG_CFG_SCRIPTS_PATH | while read pkg_exe
do
	if [ -n "$FIRST" ] ; then
		let XD_ITEM=XD_ITEM+1
		let XD_HEIGHT=XD_HEIGHT+1
		echo "XD_ITEM${XD_ITEM}=EMPTY" >> $MENU_FILE
		FIRST=
	fi

	pkg=`echo $pkg_exe | sed 's/^...//'`	
	load_lang $pkg

	PKG_LNG_VAR='LNG_MENU_CONFIG_PKG_'`make_caps "$pkg"`'_TITLE'
	PKG_CFG_TITLE="`eval echo '$'$PKG_LNG_VAR`"
	if [ -z "$PKG_CFG_TITLE" ] ; then PKG_CFG_TITLE=$pkg ; fi
	
	let XD_ITEM=XD_ITEM+1
	let XD_HEIGHT=XD_HEIGHT+1
	echo "XD_ITEM${XD_ITEM}=\"$PKG_CFG_TITLE\"" >> $MENU_FILE
	echo "XD_RUN${XD_ITEM}=${PKG_CFG_SCRIPTS_PATH}$pkg_exe"	>> $MENU_FILE
	echo "XD_HEIGHT=$XD_HEIGHT" >> $MENU_FILE
done

/bin/xdmenu $MENU_FILE
