#!/bin/sh

WPP_BIN=/bin/wpa_passphrase
TMP=/tmp/store_wireless_tmp

if [ "$1" = "" ] ; then
	/bin/store_variable WIRELESS_WPAKEY_ENC ""
	exit 0
fi

. $TS_GLOBAL
load_lang config

if [ ! -e $WPP_BIN ] ; then
	echo "Wireless package not loaded!"
	exit 1
fi

if [ "$WIRELESS_ESSID" = "" ] ; then
	echo "WIRELESS_ESSID must be set in order to store PSK!"
	exit 1
fi

if [ "`expr length \"$1\"`" -lt  "8" ] ; then
	/bin/xdmenu_msgbox "$LNG_MENU_NET_WIRELESS_STOREPSK_SHORT"
	exit 1
fi

$WPP_BIN $WIRELESS_ESSID $1 | grep -v \#psk= | grep psk= > $TMP

if [ -e $TMP ] ; then
	. $TMP
	/bin/store_variable WIRELESS_WPAKEY_ENC $psk
fi

exit 0
