#!/bin/sh

. $TS_GLOBAL
load_lang config

if [ -z "$3" ] ; then
	echo "Require params: [VAR_NAME] [TITLE] [LIST OF OPTIONS] [LABEL1] [LABEL2]...!"
	exit;
fi

VARNAME=$1
TITLE=$2
OPTIONS=$3

MENU_FILE=/tmp/vareditselect.xd

echo "
XD_TYPE=MENU
XD_CLASSNAME=var_edit_select
XD_TITLE=\"$LNG_VAR_EDIT_SELECT_TITLE\"
XD_TEXT=\"$TITLE\"
XD_MENU_EXIT=1
XD_WIDTH=54
XD_STORE_RESULT_AS=$VARNAME
" > $MENU_FILE

i=0
for option in $OPTIONS
do
	result=$option
	if [ "$option" = "NULL" ] ; then
		result=
	fi

	let p=i+4
	descr=`eval echo '$'$p`
	if [ -z "$descr" ] ; then
		descr=$option
	fi

	echo "XD_ITEM$i=\"$descr\"" >> $MENU_FILE
	echo "XD_RESULT$i=\"$result\"" >> $MENU_FILE
	let i=i+1  
done

let i=i+9
echo "XD_HEIGHT=$i" >> $MENU_FILE

/bin/xdmenu $MENU_FILE
if [ -e $MENU_FILE ] ; then rm $MENU_FILE ; fi
