/* Autogenerated by configure. Do not edit */

#include "module-defs.h"

PangoIncludedModule _pango_included_x_modules[] = {
 { _pango_basic_x_script_engine_list, _pango_basic_x_script_engine_init, _pango_basic_x_script_engine_exit, _pango_basic_x_script_engine_create },
 { NULL, NULL, NULL },
};
