/* Autogenerated by configure. Do not edit */

#include "modules.h"

extern void         _pango_basic_fc_script_engine_list (PangoEngineInfo **engines, int *n_engines);
extern PangoEngine *_pango_basic_fc_script_engine_init (GTypeModule *module);
extern void         _pango_basic_fc_script_engine_exit (void);
extern void         _pango_basic_fc_script_engine_create (const char *id);

extern void         _pango_basic_x_script_engine_list (PangoEngineInfo **engines, int *n_engines);
extern PangoEngine *_pango_basic_x_script_engine_init (GTypeModule *module);
extern void         _pango_basic_x_script_engine_exit (void);
extern void         _pango_basic_x_script_engine_create (const char *id);

