include /build/source/fbpanel/fbpanel-6.1/config.mk

SRCS = volume.c 
LIBTARGET = volume.so
install:
	$(install) 755 $(LIBDIR)/fbpanel 755 $(LIBTARGET)

include /build/source/fbpanel/fbpanel-6.1/rules.mk
