'\" t
.\"     Title: xfreerdp
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2011-08-27
.\"    Manual: xfreerdp
.\"    Source: freerdp
.\"  Language: English
.\"
.TH "XFREERDP" "1" "2011\-08\-27" "freerdp" "xfreerdp"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
xfreerdp \- FreeRDP X11 client
.SH "SYNOPSIS"
.PP

\fBxfreerdp\fR
[options] server[:port] [[options] server[:port] \&...]
.SH "DESCRIPTION"
.PP

\fBxfreerdp\fR
is an X11 Remote Desktop Protocol (RDP) client which is part of the FreeRDP project\&. An RDP server is built\-in to many editions of Windows\&. Alternative servers included xrdp and VRDP (VirtualBox)\&.
.SH "OPTIONS"
.PP
\-0
.RS 4
Attach to the admin console of the server\&.
.RE
.PP
\-a \fIbpp\fR
.RS 4
Sets the color depth for the connection to
\fIbpp\fR
bits per pixel\&. Valid values are 8, 15, 16, 24 and 32\&. The default value is the color depth of the FreeRDP\-window\&.
.RE
.PP
\-c \fIdir\fR
.RS 4
Sets the working\-dir to
\fIdir\fR\&. This parameter is only used when an AlternateShell (\-s \fIshell\fR) is requested\&.
\fIdir\fR
should contain the executable file specified in the AlternateShell\&.
.RE
.PP
\-D
.RS 4
Removes the windows decorations\&.
.RE
.PP
\-d \fIdomain\fR
.RS 4
Set the domain used in authentication to
\fIdomain\fR\&.
.RE
.PP
\-f
.RS 4
start in full screen mode\&. This mode can always be en\- and disabled using Ctrl\-Alt\-Enter\&.
.RE
.PP
\-T \fItext\fR
.RS 4
Sets the window title to
\fItext\fR\&.
.RE
.PP
\-g \fIgeometry\fR
.RS 4
Sets the size of the FreeRDP window (and of the remote desktop, when establishing a new connection)\&.
\fIgeometry\fR
can have one of the following forms:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIW\fRx\fIH\fR
\- in this case the resulting window will be of
\fIW\fRx\fIH\fR
pixels\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIP\fR% \- in this case the resulting window will be
\fIP\fR% of your screen\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
The special keyword
\fIworkarea\fR
\- in this case the resulting window will be of the same size as your workarea\&.
.RE
.sp
.RE
.PP
\-h
.RS 4
Print help\&.
.RE
.PP
\-k \fIid\fR
.RS 4
Sets the keyboard\-layout\-id to
\fIid\fR\&.
.RE
.PP
\-K
.RS 4
Do not interfere with window manager bindings (don\*(Aqt grab keyboard)\&.
.RE
.PP
\-n \fIhostname\fR
.RS 4
Set the reported client hostname to
\fIhostname\fR\&. Default is to automatically detect the hostname\&.
.RE
.PP
\-o
.RS 4
Play audio on the console instead of redirecting to the client\&.
.RE
.PP
\-p \fIpassword\fR
.RS 4
Password used in authentication\&.
.RE
.PP
\-s \fIshell\fR
.RS 4
Sets the startup\-shell to
\fIshell\fR\&. This parameter should contain a complete path to the alternate shell\&. If the alternete shell requires a different working directory use
\-c \fIdir\fR\&.
.RE
.PP
\-t \fIport\fR
.RS 4
Connect to
\fIport\fR, instead of the default 3389\&.
.RE
.PP
\-u \fIusername\fR
.RS 4
Username used in authentication\&.
.RE
.PP
\-x \fIflag\fR
.RS 4
Set the experience performance flags\&.
\fIflag\fR
can be one of:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
m \- (modem): Equivalent to 15\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
b \- (broadband): Equivalent to 1\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
l \- (lan): Equivalent to 0\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fInum\fR
\- A hexadecimal number that represents a bit\-mask, were numbers mean the following
\&\s-2\u[1]\d\s+2:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
1: Disable desktop wallpaper\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
2: Disable full\-window drag (only the window outline is displayed when the window is moved)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
4: Disable menu animations\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
8: Disable user interface themes\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
20: Disable mouse cursor shadows\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
40: Disable cursor blinking\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
80: Enable font smoothing\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
100: Enable Desktop Composition\&.
.RE
.sp
.RE
.sp
.RE
.PP
\-X \fIxid\fR
.RS 4
embed xfreerdp into window with
\fIxid\fR\&.
.RE
.PP
\-z
.RS 4
Enable compression\&.
.RE
.PP
\-\-app
.RS 4
initialize a RemoteApp connection\&. This implies \-g workarea\&.
.RE
.PP
\-\-no\-auth
.RS 4
Skips authentication\&. This is useful e\&.g\&. for the current FreeRDP server that doesn\*(Aqt yet support server\-side authentication\&.
.RE
.PP
\-\-authonly
.RS 4
Only authenticates\&. This is useful to test your credentials (username and password)\&. Returns status code 0 if the client can connect\&. Requires a username, password and connection host at the command line\&.
.RE
.PP
\-\-no\-bmp\-cache
.RS 4
Disable bitmap cache\&.
.RE
.PP
\-\-certificate\-name \fIname\fR
.RS 4
use
\fIname\fR
for the logon certificate, instead of the server name
.RE
.PP
\-\-composition
.RS 4
Enable composition (RDVH only, not to be confused with remote composition)\&.
.RE
.PP
\-\-ext \fIextname\fR
.RS 4
load extension
\fIextname\fR
.RE
.PP
\-\-no\-fastpath
.RS 4
Disables fast\-path\&. Use slow\-path packets instead, which have larger headers\&. It might be good for debugging certain issues when you suspect it might be linked to the parsing of one of the two header types\&.
.RE
.PP
\-\-from\-stdin
.RS 4
Prompts for unspecified arguments \-u username, \-p password, \-d domain and connection host\&. This is useful to hide arguments from ps\&. Also useful for scripts that will feed these arguments to the client via (what else?) stdin\&.
.RE
.PP
\-\-disable\-full\-window\-drag
.RS 4
Disable full window drag\&.
.RE
.PP
\-\-gdi \fIbackend\fR
.RS 4
GDI (Graphics Device Interface) rendering backend\&.
\fIbackend\fR
can be either sw (software) or hw (hardware)\&.
.RE
.PP
\-\-help
.RS 4
Print help\&.
.RE
.PP
\-\-ignore\-certificate
.RS 4
ignore verification of logon certificate\&.
.RE
.PP
\-\-kbd\-list
.RS 4
list all keyboard layout ids used by \-k
.RE
.PP
\-\-disable\-menu\-animations
.RS 4
Disable menu animations\&.
.RE
.PP
\-\-no\-motion
.RS 4
Don\*(Aqt send mouse motion events\&.
.RE
.PP
\-\-no\-nla
.RS 4
Disable network level authentication\&.
.RE
.PP
\-\-nsc
.RS 4
Enable NSCodec\&.
.RE
.PP
\-\-no\-osb
.RS 4
Disable off screen bitmaps\&.
.RE
.PP
\-\-plugin \fIpluginname\fR
.RS 4
load
\fIpluginname\fR
.RE
.PP
\-\-no\-rdp
.RS 4
Disable Standard RDP encryption\&.
.RE
.PP
\-\-rfx
.RS 4
Enable RemoteFX\&.
.RE
.PP
\-\-rfx\-mode
.RS 4
RemoteFX operational flags\&.
\fIflags\fR
can be either v[ideo], i[mage]), default is video\&.
.RE
.PP
\-\-ntlm \fIversion\fR
.RS 4
force NTLM protocol version to be
\fIversion\fR, which can be one of 1 or 2\&.
.RE
.PP
\-\-sec \fIproto\fR
.RS 4
force protocol security\&.
\fIproto\fR
can be one of rdp, tls or nla\&.
.RE
.PP
\-\-secure\-checksum
.RS 4
Use salted checksums with Standard RDP encryption\&.
.RE
.PP
\-\-disable\-theming
.RS 4
Disable theming\&.
.RE
.PP
\-\-no\-tls
.RS 4
Disable TLS encryption\&.
.RE
.PP
\-\-version
.RS 4
Print version information\&.
.RE
.PP
\-\-disable\-wallpaper
.RS 4
Disable wallpaper\&.
.RE
.SH "LINKS"
.PP

\m[blue]\fBhttp://www\&.freerdp\&.com/\fR\m[]
.SH "AUTHOR"
.br
.PP
The FreeRDP Team
.SH "NOTES"
.IP " 1." 4
Taken from
\m[blue]\fBMS-RDPBCGR Section 2.2.1.11.1.1.1 - Extended Info Packet\fR\m[]
.IP " 2." 4
MS-RDPBCGR Section 2.2.1.11.1.1.1 - Extended Info Packet
.RS 4
\%http://msdn.microsoft.com/en-us/library/cc240476%28v=prot.10%29.aspx
.RE
