.TH XvFreeAdaptorInfo 3 "libXv 1.0.7" "X Version 11" "libXv Functions"
.SH NAME
XvFreeAdaptorInfo \- free adaptor information
.\"
.SH SYNOPSIS
.BI "void XvFreeAdaptorInfo(XvAdaptorInfo *" p_adaptor_info ");"
.SH ARGUMENTS
.\"
.IP \fIp_adaptor_info\fR 8
Pointer to where the adaptor information is located.
.\"
.SH DESCRIPTION
.\"
.BR XvFreeAdaptorInfo (3)
frees adaptor information that was returned by
.BR XvQueryAdaptors (3).
The data structure used for adaptor information is defined in the
reference page for
.BR XvQueryAdaptors (3).
.SH SEE ALSO
.\"
.BR XvQueryAdaptors (3),
.BR XvFreeEncodingInfo (3)
