Document: lunchbox
Title: Debian lunchbox Manual
Author: <insert document author here>
Abstract: This manual describes what lunchbox is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lunchbox/lunchbox.sgml.gz

Format: postscript
Files: /usr/share/doc/lunchbox/lunchbox.ps.gz

Format: text
Files: /usr/share/doc/lunchbox/lunchbox.text.gz

Format: HTML
Index: /usr/share/doc/lunchbox/html/index.html
Files: /usr/share/doc/lunchbox/html/*.html
