/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_FPOS_POS_H)
#define CALC_HAVE_FPOS_POS_H


/* do we have fgetpos & fsetpos functions? */
#undef HAVE_FPOS_POS
#define HAVE_FPOS_POS 1  /* yes */

#undef FPOS_POS_BITS
#undef FPOS_POS_LEN
#define FPOS_POS_BITS 32
#define FPOS_POS_LEN 4


#endif /* !CALC_HAVE_FPOS_POS_H */
