/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_USTAT_H)
#define CALC_HAVE_USTAT_H


/* do we have or want ustat()? */
#define HAVE_USTAT /* yes */


#endif /* !CALC_HAVE_USTAT_H */
