/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_POSSCL_H)
#define CALC_HAVE_POSSCL_H


/* FILEPOS is not a simple value */
#undef HAVE_FILEPOS_SCALAR


#endif /* !CALC_HAVE_POSSCL_H */
