.TH vnclicense 1 "May 2012" "RealVNC Ltd" "VNC Server"
.SH NAME
vnclicense \- install, remove or check VNC\(rg Server license keys
.SH SYNOPSIS
.BI "vnclicense -add " LICENSE-KEY
.br
.BI "vnclicense -remove " LICENSE-KEY
.br
.B vnclicense -check
.br
.B vnclicense -list
.SH DESCRIPTION
.BR vnclicense
manages license keys for VNC Server.
.SH OPTIONS
.BR vnclicense
accepts the following command-line options:
.TP
.BI "-add " LICENSE-KEY
Install license key \fILICENSE-KEY\fP.  The license key will have been emailed
to you when you purchased a license for the software.
.TP
.BI "-remove " LICENSE-KEY
Remove license key \fILICENSE-KEY\fP.  \fILICENSE-KEY\fP can be either a
license key, in which case it is removed only if it is currently installed, or
a number, in which case the license key identified by that number is
removed. To see how your licenses are numbered, run \fBvnclicense -list\fP.
.TP
.B -check
Verify that the number of desktops in use does not exceed the maximum
allowed.
.B vnclicense
displays the number of active
desktops, the maximum number of desktops and a breakdown of how many
desktops each user is running. It exits with a zero return code if and
only if there are desktops available.
.TP
.B -list
List your installed license keys, together with the number of desktops
for which they are valid and the date on which they were issued. Trial
license are also listed along with the number of days for which they
are valid.
.SH NOTES
In order to add or remove license keys,
.B vnclicense
must be run by the superuser.
.SH SEE ALSO
.BR vncserver-virtual (1),
.BR vncviewer (1),
.BR vncaddrbook (1),
.BR vncpasswd (1),
.BR Xvnc (1),
.BR vncserver-x11 (1),
.BR vncinitconfig (1)
.br
http://www.realvnc.com
.SH AUTHOR
RealVNC Ltd.
