.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH ATI 4 "xf86-video-ati 7.2.0" "X Version 11"
.SH NAME
ati \- ATI video driver
.SH SYNOPSIS
.nf
.B "Section \*qDevice\*q"
.BI "  Identifier \*q"  devname \*q
.B  "  Driver \*qati\*q"
\ \ ...
.B EndSection
.fi
.SH DESCRIPTION
.B ati
is an Xorg wrapper driver for ATI video cards.  It autodetects
whether your hardware has a Radeon, Rage 128, or Mach64 or earlier class of
chipset, and loads the radeon(4),
r128(4), or mach64 driver as
appropriate.
.SH SUPPORTED HARDWARE
The
.B ati
driver supports Radeon, Rage 128, and Mach64 and earlier chipsets by loading
those drivers.  See those manpages for specific cards supported.
.SH CONFIGURATION DETAILS
Please refer to xorg.conf(5) for general configuration
details, and the specific card driver for driver configuration details.
.SH "SEE ALSO"
Xorg(1), xorg.conf(5), Xserver(1), X(7), r128(4), radeon(4)
.SH AUTHORS
See the individual driver pages for authors.
