set(PULSEAUDIO_FOUND TRUE)

set(PULSEAUDIO_VERSION_MAJOR 4)
set(PULSEAUDIO_VERSION_MINOR 0)
set(PULSEAUDIO_VERSION 4.0)
set(PULSEAUDIO_VERSION_STRING "4.0")

find_path(PULSEAUDIO_INCLUDE_DIR pulse/pulseaudio.h HINTS "/usr/include")
find_library(PULSEAUDIO_LIBRARY NAMES pulse libpulse HINTS "/usr/lib")
