# CMake generated Testfile for 
# Source directory: /source/cmake-2.8.10.2/Tests/RunCMake
# Build directory: /source/cmake-2.8.10.2/Tests/RunCMake
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(RunCMake.GeneratorExpression "/source/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/source/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/GeneratorExpression" "-DRunCMake_BINARY_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/GeneratorExpression" "-P" "/source/cmake-2.8.10.2/Tests/RunCMake/GeneratorExpression/RunCMakeTest.cmake")
ADD_TEST(RunCMake.TargetPropertyGeneratorExpressions "/source/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/source/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/TargetPropertyGeneratorExpressions" "-DRunCMake_BINARY_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/TargetPropertyGeneratorExpressions" "-P" "/source/cmake-2.8.10.2/Tests/RunCMake/TargetPropertyGeneratorExpressions/RunCMakeTest.cmake")
ADD_TEST(RunCMake.Languages "/source/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/source/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/Languages" "-DRunCMake_BINARY_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/Languages" "-P" "/source/cmake-2.8.10.2/Tests/RunCMake/Languages/RunCMakeTest.cmake")
ADD_TEST(RunCMake.ObjectLibrary "/source/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/source/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/ObjectLibrary" "-DRunCMake_BINARY_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/ObjectLibrary" "-P" "/source/cmake-2.8.10.2/Tests/RunCMake/ObjectLibrary/RunCMakeTest.cmake")
ADD_TEST(RunCMake.build_command "/source/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/source/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/build_command" "-DRunCMake_BINARY_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/build_command" "-P" "/source/cmake-2.8.10.2/Tests/RunCMake/build_command/RunCMakeTest.cmake")
ADD_TEST(RunCMake.find_package "/source/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/source/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/find_package" "-DRunCMake_BINARY_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/find_package" "-P" "/source/cmake-2.8.10.2/Tests/RunCMake/find_package/RunCMakeTest.cmake")
ADD_TEST(RunCMake.include "/source/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/source/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/include" "-DRunCMake_BINARY_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/include" "-P" "/source/cmake-2.8.10.2/Tests/RunCMake/include/RunCMakeTest.cmake")
ADD_TEST(RunCMake.include_directories "/source/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/source/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/include_directories" "-DRunCMake_BINARY_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/include_directories" "-P" "/source/cmake-2.8.10.2/Tests/RunCMake/include_directories/RunCMakeTest.cmake")
ADD_TEST(RunCMake.list "/source/cmake-2.8.10.2/bin/cmake" "-DCMAKE_MODULE_PATH=/source/cmake-2.8.10.2/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/list" "-DRunCMake_BINARY_DIR=/source/cmake-2.8.10.2/Tests/RunCMake/list" "-P" "/source/cmake-2.8.10.2/Tests/RunCMake/list/RunCMakeTest.cmake")
