include /source/fbpanel/fbpanel-6.1/config.mk

SUBDIRS = systray launchbar space
#SUBDIRS = taskbar launchbar space menu pager mem chart cpu net
#SUBDIRS += systray dclock wincmd icons separator image
#SUBDIRS += deskno tclock genmon deskno2 meter volume battery

include /source/fbpanel/fbpanel-6.1/rules.mk
