ifndef SND_TOPDIR
SND_TOPDIR=../..
endif

include $(SND_TOPDIR)/toplevel.config
include $(SND_TOPDIR)/Makefile.conf

export-objs  := wss_lib.o

include $(SND_TOPDIR)/alsa-kernel/isa/wss/Makefile

include $(SND_TOPDIR)/Rules.make
